### ISSUE TITLE
boxplot_abudance does not plot to corresponding pair sample if its absent?

### ISSUE THREAD

**Issue by manasishah86** [microbiome/microbiome#10]
Hi Antagomir,

Thanks for developing the package,

I would like to be able to plot boxplot_abudance on paired fecal and biopsy samples (paired as in they are obtained from the same participant). What happens if that particular OTU occurs in fecal but does not occur in biopsy, right now it's pairing multiple samples in the biopsy group to just one sample in the fecal group (which is not the exact corresponding pair)
Can you help me interpret the plot better? I would like that each biopsy sample is paired with its corresponding fecal counterpart at 0 even if that OTU is absent in the plot.
Do multiple lines mean that there are multiple overlapping points at that same 'signal' value? Because it happens at non-zero signal values as well. 

Also,  is the lower bound of Y axis set to 0? I tried to set the limits in ggplot2 it interfered with the scale10 transformation. If it can show 0 that will be helpful

Finally, in the syntax, 
`boxplot_abundance <- function (pseq, x, y, line = NULL, color = NULL, log10 = TRUE, title = NULL) ` 

if I run the function boxplot_abundance function independently (i.e without the package, sorry I have set a version control since I have multiple dissertation analyses with various dependencies and cannot update all packages for successful microbiome installation currently), y does not take a Family/Genus "f__Prevotellaceae" name as suggested in your vignette. Rather takes an OTUID for y. Is that normal?

![rplot01](https://cloud.githubusercontent.com/assets/16874229/16907001/cd0f0290-4c84-11e6-8f7a-d89fd944a961.jpeg)

 Thanks a lot for your time again

**Comment by antagomir** [comment]
I have now splitted this into individual issues. See #11 #12 #13
