### ISSUE TITLE
Error with aggregate_taxa() function

### ISSUE THREAD

**Issue by caijian89** [microbiome/microbiome#100]
Hello,
I am a beginner to use the microbiome packages, I tried the example data such as "dietswap" with aggreagate_taxa(), and it was successful. However, I got an error message when I tried the "GlobalPatterns" dataset from "phyloseq" packages. I do not understand where is going wrong with that, the code is listed:
> s<-aggregate_taxa(GlobalPatterns,level = "Phylum")
Error in aggregate_taxa(GlobalPatterns, level = "Phylum") : 
  The taxa are not found in tax_table in aggregate_taxa
> rank_names(GlobalPatterns)
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family" 
[6] "Genus"   "Species"
> rank_names(dietswap)
[1] "Phylum" "Family" "Genus"

**Comment by antagomir** [comment]
Fixed. Please test and report.
