### ISSUE TITLE
read_phyloseq - microbiome version issue?

### ISSUE THREAD

**Issue by yaminijangir** [microbiome/microbiome#103]
Hi,

I have used this function before without any issues in my earlier PC. However, recently I upgraded my computer and installed new versions of the all packages. I am getting the following issue -

> rm(list=ls())
>pseq <- read_phyloseq("final.an.0.02.filter.shared", "final.an.0.02.cons.taxonomy", "final.metadata.csv", type = "mothur")
Time to complete depends on OTU file size
Error in vapply(m.otu[, c(2:(ncol(m.otu) - 1))], as.numeric, 1) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 29

I have attached the old and new sessionInfo. Let me know if I am missing something. 

[sessionInfo_new.txt](https://github.com/microbiome/microbiome/files/2725540/sessionInfo_new.txt)
[sessionInfo_old_VJO.txt](https://github.com/microbiome/microbiome/files/2725541/sessionInfo_old_VJO.txt)

**Comment by antagomir** [comment]
Thanks for the report. 

Without seeing the files it is difficult to debug exactly. My impression is that the m.otu file is not properly read or matched, and as a result the m.otu matrix has a wrong type. This is a guess.

Not sure how rapidly I could debug this. If you have a chance to try, the function that is called is [read_mothur2phyloseq](https://github.com/microbiome/microbiome/blob/master/R/read_mothur2phyloseq.R). If you could try it line by line, perhaps the problem becomes obvious and hence the solution, too (PRs welcome). If not, you could store the problematic input as an RData file and indicate on which line the code fails exactly. This can speed up the process.

**Comment by vfrazier1331** [comment]
I am trying to use the read_mothur2phyloseq function and the error occurs on the m.otu <- read.table() step, which yields the error: "no lines available in input." I am using a .shared file straight out of mothur. Do you know how to solve this?

**Comment by antagomir** [comment]
This may be related to the use of vapply vs. sapply. We are advised to switch to vapply but this causes problems currently. I tried to fix and change to sapply for a temporary fix. Can you test (new devel version 1.7.22), and report if it works now?

**Comment by thedam** [comment]
Hi,
I have the same problem.
How can I change vapply to sapply in `read_phyloseq` function? 
what do you mean by "devel" version?

`pseq2 <- read_phyloseq(otu.file="example.final.opti_mcc.shared", taxonomy.file="example.final.opti_mcc.0.03.cons.taxonomy", type = "mothur")`

[example.final.opti_mcc.zip](https://github.com/microbiome/microbiome/files/3922026/example.final.opti_mcc.zip)

**Comment by thedam** [comment]
also I can't import a biom table:
python:
```
qiime tools export --input-path otu-table-flt.qza --output-path .
Exported otu-table-flt.qza as BIOMV210DirFmt to directory export
```
R:
```
biom.file <- "export/feature-table.biom"
meta.file <- "samples_meta.tsv"
pseq1 <- read_phyloseq(otu.file=biom.file, taxonomy.file=NULL, metadata.file=meta.file, type = "biom")

Time to complete depends on OTU file size
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
or maybe I'm exporting wrong biom?

**Comment by antagomir** [comment]
Which version you are using? I am able to run your above example (with zip) using the latest devel version 1.9.14 of microbiome pkg.

**Comment by antagomir** [comment]
Also updated from sapply to vapply in the latest devel version 1.9.15 now (in github master)
