### ISSUE TITLE
Reproducibility of microbiome package online tutorial

### ISSUE THREAD

**Issue by davidbarscortina** [microbiome/microbiome#105]
Hello everybody,

I'm newbie in the use of microbiome package. I apologise but I don't understand why doesn't run the example in my R!

However, and I'm uncapable why, I cannot reproduce the example stated on: http://microbiome.github.io/microbiome/Diversity.html 

My R version is 3.5.2, 32 bytes Windows based system.

In detail, I wrote:

```library(phyloseq)
library(microbiome)
library(knitr)
data(dietswap)
print(dietswap)
pseq <- dietswap
tab <- alpha(pseq, index = "all")
tab <- alpha(pseq)```

And I obtained the following errors.

For the command:
`<tab <- alpha(pseq, index = "all")>`

I obtained:

```Error in alpha(pseq, index = "all") : unused argument (index = "all")```

And for the command:

tab <- alpha(pseq)

I obtained:

```Error in as.character.default(col) : 
  no method for coercing this S4 class to a vector```

Thanks on advance for your help,

David Bars-Cortina
PhD Student
University of Lleida
Catalonia

**Comment by antagomir** [comment]
Is this because your code seems to include triple quotes (```) - these are not part of R code?

**Comment by davidbarscortina** [comment]
I didn't write triple quotes(```) in my R code. I only write here in GitHub in order to highlight that's a R code.

Apologise me for the inappropriate annotation.

Thanks another time.

**Comment by antagomir** [comment]
For me the example works. Can you include the output of your sessionInfo() ?

Are you sure that other loaded packages are not providing "alpha". You could try to use microbiome::alpha

**Comment by davidbarscortina** [comment]
I attach you the R script used with the console output obtained. I hope that it will be useful to solve this issue. I've included also sessionInfo() command.

Many thanks.

[startingwithmicrobiome.zip](https://github.com/microbiome/microbiome/files/2855850/startingwithmicrobiome.zip)

**Comment by antagomir** [comment]
Hi - we will not work with zip files (for various reasons). Can you share the code openly, and everyone can readily see it and comment on it. You can for instance share a github/gist, or show the code and sessionInfo() output here if they are short.

**Comment by davidbarscortina** [comment]
Hi. Ok, no problem. 

That's the code:

library(microbiome)
#Loading required package: phyloseq
#Loading required package: ggplot2

#microbiome R package (microbiome.github.com)



#Copyright (C) 2011-2018 Leo Lahti et al. <microbiome.github.io>
  
  
#  Attaching package: 'microbiome'

#The following object is masked from 'package:base':
  
#  transform

library(knitr)
data(dietswap)
print(dietswap)
#phyloseq-class experiment-level object
#otu_table()   OTU Table:         [ 130 taxa and 222 samples ]
#sample_data() Sample Data:       [ 222 samples by 8 sample variables ]
#tax_table()   Taxonomy Table:    [ 130 taxa by 2 taxonomic ranks ]

pseq <- dietswap
tab <- alpha(pseq, index = "all")
#Error in alpha(pseq, index = "all") : unused argument (index = "all")

tab <- alpha(pseq)
#Error in as.character.default(col) : 
#  no method for coercing this S4 class to a vector

tab <- microbiome::alpha(pseq, index = "all")
#Error: 'alpha' is not an exported object from 'namespace:microbiome'

sessionInfo()
#R version 3.5.2 (2018-12-20)
#Platform: i386-w64-mingw32/i386 (32-bit)
#Running under: Windows 7 (build 7601) Service Pack 1

#Matrix products: default

#locale:
#  [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
#[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

#attached base packages:
#  [1] stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#  [1] knitr_1.21       microbiome_1.4.2 ggplot2_3.1.0    phyloseq_1.26.1 

#loaded via a namespace (and not attached):
#  [1] jsonlite_1.6        ade4_1.7-13         reshape2_1.4.3      cluster_2.0.7-1     rstudioapi_0.9.0   
#[6] magrittr_1.5        gtable_0.2.0        zlibbioc_1.28.0     multtest_2.38.0     tidyr_0.8.2        
#[11] data.table_1.12.0   XVector_0.22.0      BiocGenerics_0.28.0 pillar_1.3.1        foreach_1.4.4      
#[16] stringr_1.4.0       splines_3.5.2       Rhdf5lib_1.4.2      dplyr_0.7.8         rhdf5_2.26.2       
#[21] lattice_0.20-38     survival_2.43-3     tidyselect_0.2.5    plyr_1.8.4          Biostrings_2.50.2  
#[26] igraph_1.2.3        iterators_1.0.10    pkgconfig_2.0.2     Matrix_1.2-15       R6_2.3.0           
#[31] IRanges_2.16.0      xfun_0.4            stats4_3.5.2        colorspace_1.4-0    Biobase_2.42.0     
#[36] bindrcpp_0.2.2      S4Vectors_0.20.1    stringi_1.2.4       lazyeval_0.2.1      codetools_0.2-16   
#[41] vegan_2.5-4         tibble_2.0.1        mgcv_1.8-27         compiler_3.5.2      bindr_0.1.1        
#[46] withr_2.1.2         munsell_0.5.0       Rcpp_1.0.0          MASS_7.3-51.1       parallel_3.5.2     
#[51] assertthat_0.2.0    biomformat_1.10.1   permute_0.9-4       tools_3.5.2         ape_5.2            
#[56] scales_1.0.0        crayon_1.3.4        glue_1.3.0          purrr_0.3.0         rlang_0.3.1        
#[61] nlme_3.1-137        grid_3.5.2

**Comment by antagomir** [comment]
Ok can you try to replace "alpha" with "microbiome::alpha" to indicate package.

**Comment by davidbarscortina** [comment]
Yes of course.

Then, appears the following error:

 tab <- microbiome::alpha(pseq, index = "all")
Error: 'alpha' is not an exported object from 'namespace:microbiome'

**Comment by antagomir** [comment]
Ok, and the output of sessionInfo() .. ?

**Comment by davidbarscortina** [comment]
Yes of course. Excuse me...

> library(microbiome)
Loading required package: ggplot2
RStudio Community is a great place to get help: https://community.rstudio.com/c/tidyverse.

microbiome R package (microbiome.github.com)
    


 Copyright (C) 2011-2018 Leo Lahti et al. <microbiome.github.io>


Attaching package: ‘microbiome’

The following object is masked from ‘package:base’:

    transform

> library(knitr)
> data(dietswap)
> print(dietswap)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 130 taxa and 222 samples ]
sample_data() Sample Data:       [ 222 samples by 8 sample variables ]
tax_table()   Taxonomy Table:    [ 130 taxa by 2 taxonomic ranks ]
> pseq <- dietswap
> tab <- microbiome::alpha(pseq, index = "all")
Error: 'alpha' is not an exported object from 'namespace:microbiome'
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.21       microbiome_1.4.2 ggplot2_3.1.0    phyloseq_1.26.1 

loaded via a namespace (and not attached):
 [1] jsonlite_1.6        ade4_1.7-13         reshape2_1.4.3      cluster_2.0.7-1     rstudioapi_0.9.0   
 [6] magrittr_1.5        gtable_0.2.0        zlibbioc_1.28.0     multtest_2.38.0     tidyr_0.8.2        
[11] data.table_1.12.0   XVector_0.22.0      BiocGenerics_0.28.0 pillar_1.3.1        foreach_1.4.4      
[16] stringr_1.4.0       splines_3.5.2       Rhdf5lib_1.4.2      dplyr_0.7.8         rhdf5_2.26.2       
[21] lattice_0.20-38     survival_2.43-3     tidyselect_0.2.5    plyr_1.8.4          Biostrings_2.50.2  
[26] igraph_1.2.3        iterators_1.0.10    pkgconfig_2.0.2     Matrix_1.2-15       R6_2.3.0           
[31] IRanges_2.16.0      xfun_0.4            stats4_3.5.2        colorspace_1.4-0    Biobase_2.42.0     
[36] bindrcpp_0.2.2      S4Vectors_0.20.1    stringi_1.2.4       lazyeval_0.2.1      codetools_0.2-16   
[41] vegan_2.5-4         tibble_2.0.1        mgcv_1.8-27         compiler_3.5.2      bindr_0.1.1        
[46] withr_2.1.2         munsell_0.5.0       Rcpp_1.0.0          MASS_7.3-51.1       parallel_3.5.2     
[51] assertthat_0.2.0    biomformat_1.10.1   permute_0.9-4       tools_3.5.2         ape_5.2            
[56] scales_1.0.0        crayon_1.3.4        glue_1.3.0          purrr_0.3.0         rlang_0.3.1        
[61] nlme_3.1-137        grid_3.5.2

**Comment by antagomir** [comment]
Ok - you are using an old version of the microbiome package (1.4.2). Current devel version is 1.5.28 and the alpha function is new. You can install the development version with devtools::install_github("microbiome/microbiome")

**Comment by davidbarscortina** [comment]
Ok,

Apologise me but I cannot install properly the development version. I have a problem with package igraph.

I've also installed by separate (through install.packages command) but doesn't appear after in my packages folder...

However, meanwhile I will use to calculate alpha diversity through phyloseq package. The other commands (gini, coverage....) works perfectly with microbiome package.

I will wait for the next update of the microbiome package in Bioconductor.
Kind regards




In detail:
library(devtools)
devtools::install_github("microbiome/microbiome")

Downloading GitHub repo microbiome/microbiome@master
Skipping 12 packages ahead of CRAN: Biobase, BiocGenerics, biomformat, Biostrings, IRanges, multtest, phyloseq, rhdf5, Rhdf5lib, S4Vectors, XVector, zlibbioc
Installing 3 packages: igraph, Rtsne, stringi

  There are binary versions available but the source versions are later:
        binary source needs_compilation
igraph   1.2.3  1.2.4              TRUE
stringi  1.2.4  1.3.1              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/igraph_1.2.3.zip'
Content type 'application/zip' length 9153124 bytes (8.7 MB)
downloaded 8.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/Rtsne_0.15.zip'
Content type 'application/zip' length 698431 bytes (682 KB)
downloaded 682 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/stringi_1.2.4.zip'
Content type 'application/zip' length 15268101 bytes (14.6 MB)
downloaded 14.6 MB

package ‘igraph’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘igraph’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.4.0  devtools_2.0.1

loaded via a namespace (and not attached):
 [1] withr_2.1.2         ggplot2_3.1.0       ps_1.3.0            tidyselect_0.2.5    rprojroot_1.3-2     pkgconfig_2.0.2    
 [7] compiler_3.5.2      prettyunits_1.0.2   fs_1.2.6            parallel_3.5.2      Rcpp_1.0.0          cli_1.0.1          
[13] plyr_1.8.4          tools_3.5.2         pkgbuild_1.0.2      memoise_1.1.0       R6_2.3.0            bindrcpp_0.2.2     
[19] bindr_0.1.1         purrr_0.3.0         BiocGenerics_0.28.0 scales_1.0.0        assertthat_0.2.0    curl_3.3           
[25] digest_0.6.18       gtable_0.2.0        foreach_1.4.4       rstudioapi_0.9.0    backports_1.1.3     desc_1.2.0         
[31] munsell_0.5.0       grid_3.5.2          colorspace_1.4-0    glue_1.3.0          rlang_0.3.1         processx_3.2.1     
[37] callr_3.1.1         magrittr_1.5        lazyeval_0.2.1      crayon_1.3.4        dplyr_0.7.8         pillar_1.3.1       
[43] remotes_2.0.2       iterators_1.0.10    codetools_0.2-16    pkgload_1.0.2       tibble_2.0.1        sessioninfo_1.1.1  
>

**Comment by microsud** [comment]
Hi,
Usually when updating packages it is better to restart Rstudio. Some packages remain "loaded" in environment and give errors when installing other packages from GitHub. Let us know if it works.

Cheers,
Sudarshan

**Comment by antagomir** [comment]
Or if it doesn't you can try to uninstall igraph.

**Comment by davidbarscortina** [comment]
Thank you but sorry but I'm uncapable to solve this problem. Also I tried with detach() R function but still appears the problem now with dplyr package:

Error: (converted from warning) cannot remove prior installation of package ‘dplyr’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by antagomir** [comment]
This is a more generic installation problem. I am not sure how to solve but it is not specific to microbiome pkg.

**Comment by davidbarscortina** [comment]
Ok. Thank you. Nevertheless, all the other microbiome functions works me well.

In addition,  and I ask here because I've been uncapable to find out which is the meaning (the purpose) of detection value used in core() function. 

I understand the prevalence value biological meaning but not for detection threshold.

I really appreciate your help and apologise me if this is not an adequate site to post my specific doubt.

**Comment by antagomir** [comment]
Ok thanks for feedback. 

The detection argument in the core function: by default prevalence uses detection = 0 i.e. anything that has non-zero (positive) abundance will count in estimating population prevalence. But: sometimes we like to ask "which OTUs are detected at 20% prevalence in abundance that exceeds 5 reads?". This would pick those OTUs that have more than 5 reads in >20% of the samples. Or, if you do compositionality transformation for the data then detection would refer to relative abundance (ie detection = 1/100 would mean 1% relative abundance). For instance: core(transform(physeq, "compositional"), detection = 1/100, prevalence = 50/100)

**Comment by davidbarscortina** [comment]
Thanks a lot antagomir!!!
