### ISSUE TITLE
evenness function - possible error

### ISSUE THREAD

**Issue by as703** [microbiome/microbiome#110]
I've come accross a potential error in the pielou evenness function. Very happy to be proved wrong here but the microbiome and vegan packages do not seem to produce the same result with sample data. Here is an example

`
require(microbiome)
require(vegan)

##Analysis from microbiome package
data(dietswap)
d <- evenness(dietswap, 'pielou')

## Analysis using vegan package. Note instructions from vegan manual
Species richness (S) and Pielou's evenness (J):
#S <- specnumber(BCI) ## rowSums(BCI > 0) does the same...
#J <- H/log(S)
x <- t(abundances(dietswap)) # Create vegan compatible OTU table
H <- diversity(x, index="shannon")
S <- specnumber(x)
J <- as.data.frame(H/log(S))

`
From the above "d" and "J" give different values for pielou evenness.

I'd be very interested in any insight.

Many thanks

**Comment by antagomir** [comment]
Thanks for reporting. We indeed identified a small nasty bug deep in the code. It is fixed now in 1.5.29 and should give identical results with vegan.
