### ISSUE TITLE
theme_set boxplot_abundance

### ISSUE THREAD

**Issue by biobee** [microbiome/microbiome#114]
Hi Leo,

In microbiome/R/boxplot_abundance.R (line 60), the active ggplot theme is changed to  "theme_set(theme_bw(20))", resulting in a global change. Would it be an option not to change plotting themes (globally) and/or leave it to the user?

Best wishes,

**Comment by antagomir** [comment]
Fair point. I have now removed pre-defined themes from the R functions in version 1.8.1 that was just pushed to github/master.
