### ISSUE TITLE
aggregate_taxa: Remove NA taxa

### ISSUE THREAD

**Issue by biobee** [microbiome/microbiome#115]
Thanks for the update to aggregate_taxa! This version works fine.

The new aggregate_taxa has some new params:
aggregate_taxa <- function(x, level, rm.na = TRUE, verbose = FALSE)

rm.na T/F for "Remove NA taxa" seems not to work. In the code itself I could not find that the value of this rm.na param is used.

Best,

**Comment by antagomir** [comment]
Thanks. This was also a legacy argument that I have now removed in the latest devel version 1.9.12
