### ISSUE TITLE
divergence function using phyloseq distance methods 

### ISSUE THREAD

**Issue by vianka16** [microbiome/microbiome#122]
Hi, 
I am trying to use the divergence function using the phyloseq distance 
methods (e.g "unifrac"), but I get an error. Methods from vegan work 
fine. I guess I am not doing a good job at specifying the coreset argument (default "NULL" in the  example below)

data(dietswap)
b <- divergence(subset_samples(dietswap, nationality == 'AFR'))
> beta_unifrac<- divergence(subset_samples(dietswap, nationality == 'AFR'), method="unifrac")
Error in eval(parse(text = method)) : object 'unifrac' not found

Thanks!

**Comment by antagomir** [comment]
There is no "unifrac" method implemented in the microbiome R package, and I could not find this examples from the current tutorials. Where this is from?

**Comment by vianka16** [comment]
method: dissimilarity method: any method available via stats::cor or
          phyloseq::distance function. Note that some methods ("jsd"
          for instance) do not work with the group divergence.

**Comment by vianka16** [comment]
okay, maybe I misunderstood the documentation.

**Comment by antagomir** [comment]
Ah yes. This is why I did not find it by grep. This was implemented some years ago. Indeed unifrac is not among the available methods atm. Sorry for the confusion, we may have to improve documentation
