### ISSUE TITLE
Association Analysis for phyloseq formatted data

### ISSUE THREAD

**Issue by marcell2** [microbiome/microbiome#124]
I am having issues converting my phyloseq object to the correct format in order to run the association analysis. If anyone can provide a workflow it would be greatly appreciated.

**Comment by antagomir** [comment]
Hi - this function is for fast preliminary exploration only. Do the examples on [this page](https://microbiome.github.io/tutorials/Heatmap.html) help? We are aiming to improve the tutorial over time so suggestions are welcome.

**Comment by antagomir** [comment]
Closing this in absence of follow-up info. We can reopen if new information will appear.
