### ISSUE TITLE
boxplot_abundance labels

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#13]
#in the syntax,
boxplot_abundance <- function (pseq, x, y, line = NULL, color = NULL, log10 = TRUE, title = NULL)

if I run the function boxplot_abundance function independently (without the package), y does not take a Family/Genus "f__Prevotellaceae" name as suggested in your vignette. Rather takes an OTUID for y. Is that normal?

**Comment by antagomir** [comment]
Can you please provide a reproducible example and links to the specific vignette page that you refer to ? Otherwise it takes more time for me to find out all details and fixing the bug will be delayed an unknown amount of time.

**Comment by manasishah86** [comment]
Hi Leo, I had one more request for a feature enhancement. I am trying to figure it out myself. 
It would be great, if in this paired boxplot_abudance function, we could show the direction of change for each paired points i.e the line is red if the "signal" is increasing from time 1 to time 2 for that paired sample and is green if the "signal" is decreasing from time 1 to time 2 for another pair. Somewhat like this:

![sample_paired_image](https://cloud.githubusercontent.com/assets/16874229/17076078/1d96aae6-506e-11e6-9ed4-d8604b89ff3e.gif)

Could you kindly indicate a suitable modifications or suggestions for this?
Thanks,
Manasi

**Comment by antagomir** [comment]
Please test and report back. Further pull requests are also welcome.
