### ISSUE TITLE
Example data sets

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#131]
Some time series data sets need to be added for examples.

**Comment by microsud** [comment]
Created an example database pkg for microbiome based on deblur ESV/ASV/sOTU data from earth microbiome project. Includes the moving pictures dataset from [Caporaso, J. Gregory, et al. "Moving pictures of the human microbiome." Genome biology 12.5 (2011): R50.](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2011-12-5-r50?report=reader). Only as examples and not for actual research questions. [jeevanuDB](https://github.com/microsud/jeevanuDB). It can be used to address most of the queries we get regarding QIIME2/DADA2 output files.
