### ISSUE TITLE
Obtaining matrix of p value

### ISSUE THREAD

**Issue by XingXiang2020** [microbiome/microbiome#132]
Hi, Karoline! I would like to obtain matrix of p value using Function getPval, but it just produce one p value from dataframe, could you tell me how to generate the matrix of p value. Thank you

**Comment by antagomir** [comment]
Hi @XingXiang2020 - can you specify which package and function this is about?

**Comment by XingXiang2020** [comment]
I use function getPval in R package barebonesCoNet (https://github.com/hallucigenia-sparsa/seqgroup/blob/master/R/barebonesCoNet.R). Have you give me some suggests?

**Comment by antagomir** [comment]
Right. That is a different package than the one where we are chatting now. My suggestion is that you leave an issue in [seqgroup](https://github.com/hallucigenia-sparsa/seqgroup/) github page.

**Comment by XingXiang2020** [comment]
Thank you very much
