### ISSUE TITLE
ERROR using example datasets

### ISSUE THREAD

**Issue by GaioTransposon** [microbiome/microbiome#133]
Hi, thank you for your tool, 
I installed through BiocManager::install("microbiome")
and getting this error message: 

> library(microbiome)
> library(knitr)
> data(dietswap)
> x <- dietswap
> # Compositional data 
> x2 <- microbiome::transform(x, "compositional")
Error in validObject(.Object) : 
  invalid class “taxonomyTable” object: superclass "vector_OR_Vector" not defined in the environment of the object's class

Version info:                
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

**Comment by antagomir** [comment]
I cannot reproduce the bug. 

Can you try to do this with the latest devel version 

`devtools::install_github("microbiome/microbiome")`

then report if the problem persists, and what is the exact version number (output of sessionInfo())

**Comment by GaioDany** [comment]
yes that solved the problem thank you :)

**Comment by microsud** [comment]
Old issue already solved
