### ISSUE TITLE
Wrong in 'Beta diversity and microbiome divergence'

### ISSUE THREAD

**Issue by guangingmai** [microbiome/microbiome#134]
When i followed the tutorial on the [website](https://microbiome.github.io/tutorials/Betadiversity.html) at last content, i.e. content of 'Inter-individual divergence / spread', it gave me something error messages which i don't know how to fix it.
The detail information is following:
~~~
pseq <- peerj32$phyloseq
b.pla <- divergence(subset_samples(pseq, group == "Placebo"),
   apply(abundances(subset_samples(pseq, group == "Placebo")), 1, median))

## Error messages output:
## Error in (function (classes, fdef, mtable)  : 
##  unable to find an inherited method for function ‘distance’ for signature ‘"otu_table", "numeric"’
## In addition: Warning message:
## In if (method %in% c("spearman", "pearson", "kendall")) { :
##  the condition has length > 1 and only the first element will be used
~~~
My `microbiome` package version is 1.8.0.

**Comment by antagomir** [comment]
Can you update to the latest version with

devtools::install_github("microbiome/microbiome") and then report both microbiome and R version if the problem persists?

**Comment by antagomir** [comment]
Closing this in absence of follow-up info. We can reopen if new information will appear.
