### ISSUE TITLE
how to extract otu table with taxonomy×sample?

### ISSUE THREAD

**Issue by guangingmai** [microbiome/microbiome#135]
I have a phyloseq object, and now i want to extract the otu table where the row are taxonomy names and the column are sample names. And i want to know how to extract specific taxonomic rank in the otu table, i.e. Phylumn×sample, Order×sample... . Can anyone tell me how to achieve it?

**Comment by antagomir** [comment]
Have you checked the tutorials for phyloseq package and [for microbiome package](https://microbiome.github.io/tutorials/)? They have answers to all this.

To retrieve abundance table, you can use for instance microbiome::abundances(x)

To retrieve different ranks, look at the various merge and aggregate functions in those two packages.
