### ISSUE TITLE
Warning message: In RColorBrewer::brewer.pal(n, pal) :   n too large, allowed maximum for palette Paired is 12 Returning the palette you asked for with that many colors

### ISSUE THREAD

**Issue by atangomo** [microbiome/microbiome#136]
Hi Everyone,

I been trying to do Stacked bar plots representing relative abundances of the different phyla in my different sample location (5).

However, the function had already had fixed the maximum number taxa to be used which is 12 while I have arrow 25 phyla that I want to plot. Could you please tell me how to customize the script for it to include as many taxa I want no only the 10 top taxa. This is what I used: 

##  Load packages

library(microbiome) # data analysis and visualisation
library(phyloseq) # also the basis of data object. Data analysis and visualisation
library(RColorBrewer) # nice color options
library(ggpubr) # publication quality figures, based on ggplot2
library(dplyr) # data handling  

pse <- readRDS("./phyobjects/armel_physeq.rds")

# use print option to see the data saved as phyloseq object.

print(pse)

################# Barplots count ####################

pse.com <- pse

# if you have dada2/deblur output and sequences as taxa names, then you can change them as follows
taxa_names(pse.com) <- paste0("ASV_", rownames(tax_table(pse.com)))

# We need to set Palette
taxic <- as.data.frame(x = pse.com@tax_table) # this will help in setting large color options

# colourCount = length(unique(taxic$Family))  #define number of variable colors based on number of Family (change the level accordingly to phylum/class/order)
# getPalette = colorRampPalette(brewer.pal(12, "Paired"))  # change the palette as well as the number of colors will change according to palette.

taxic$OTU <- rownames(taxic) # Add the OTU ids from OTU table into the taxa table at the end.
colnames(taxic) # You can see that we now have extra taxonomy levels.

## [1] "Domain" "Phylum" "Class"  "Order"  "Family" "Genus"  "OTU"

taxmat <- as.matrix(taxic) # convert it into a matrix.
new.tax <- tax_table(taxmat) # convert into phyloseq compatible file.
tax_table(ps1.com) <- new.tax # incroporate into phyloseq Object

# now edit the unclassified taxa
tax_table(ps1.com)[tax_table(ps1.com)[, "Phylum"] == "", "Phylum"] <- "Unclassified Phylum"

# it would be nice to have the Taxonomic names in italics.
# for that we set this

guide_italics <- guides(fill = guide_legend(label.theme = element_text(
  size = 15,
  face = "italic", colour = "Black", angle = 0
)))

## Now we need to plot at family level, we can do it as follows:

# first remove the phy_tree

ps1.com@phy_tree <- NULL

# Second merge at Phylum level

ps1.com.phylu <- microbiome::aggregate_taxa(ps1.com, "Phylum")

plot.composition.COuntAbun <- plot_composition(ps1.com.fam) + theme(legend.position = "bottom") +
  scale_fill_brewer("Phylum", palette = "Paired") + theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Relative abundance") + guide_italics + theme(legend.title = element_text(size = 18))

plot.composition.COuntAbun

#ggsave("./Test_Outputfiles/Family_barplot_CountAbundance.pdf", height = 6, width = 8)

#################    Barplot relative abundance  #############################

#Make it relative abundance

# the previous pseq object ps1.com.phylu is only counts.

# Use traqnsform function of microbiome to convert it to rel abun.

ps1.com.phylu.rel <- microbiome::transform(ps1.com.phylu, "compositional")

plot.composition.relAbun <- plot_composition(group_by = "Organlocation", ps1.com.phylu.rel,
                                             sample.sort = "scientific_name",
                                             x.label = "env_material") 
plot.composition.relAbun <- plot.composition.relAbun + theme(legend.position = "left") 
plot.composition.relAbun <- plot.composition.relAbun + scale_fill_brewer("Phylum", palette = "Paired") + theme_bw() 
plot.composition.relAbun <- plot.composition.relAbun + theme(axis.text.x = element_text(angle = 40)) 
plot.composition.relAbun <- plot.composition.relAbun + ggtitle("Relative abundance") + guide_italics + theme(legend.title = element_text(size = 18))

print(plot.composition.relAbun)

This is the error I am getting after several trial to include the colour

In RColorBrewer::brewer.pal(n, pal) :
  n too large, allowed maximum for palette Paired is 12
Returning the palette you asked for with that many colors

Thanks for your help

**Comment by antagomir** [comment]
Can you provide a reproducible example with some demo data?

**Comment by atangomo** [comment]
Dear Dr Leo,

Hope this email finds you well.

This is some demo data that I was able to prepare. Since 1 month, I am
reading and using your pipeline and willing to do a customize stake plot at
4 taxonomy level: phylum, class, family and genus. But still got the same
error when I am trying to do more than 12 at each taxa level:




*Warning message:  In RColorBrewer::brewer.pal(n, pal) :  n too large,
allowed maximum for palette Paired is 12Returning the palette you asked for
with that many colours.*


Event subsetting the sample seem also difficult because I also have this
error :



*Error in dimnames(x) <- dn :   length of 'dimnames' [1] not equal to array
extent*

This is attached the demo.data as well as the script I will be glad If you
can assist Me. Thanks in advance.

Kind regards.

Armel Tangomo Ngnintedem

**Comment by antagomir** [comment]
Can I have the data and code by email? In general, it is not advisable to plot over 10 different discrete colors. 

Can't comment on the subsetting comment without seeing the code.

**Comment by atangomo** [comment]
The Winrar data was attached to the email

**Comment by atangomo** [comment]
I have attached the R code as well as the reproducible data to the email.

**Comment by atangomo** [comment]
#subset to only the bacteria phylum

armel_phy_bact <- subset_taxa(armel_physeq, Phylum=="Bacteriodetes")

#Error in dimnames(x) <- dn : 
  #length of 'dimnames' [1] not equal to array extent

Bacteroidetes <- subset_taxa(armel_physeq, Phylum=="p__Bacteroidetes")

#Error in dimnames(x) <- dn : 
  #length of 'dimnames' [1] not equal to array extent


#plot to see the what we have 

colnames(tax_table(armel_phy_bact))

plot_bar(armel_phy_bact, fill = "Class")

plot_bar(armel_phy_bact, fill = "Order")

#to subset by the class Actinobacteria

armel_phy_bact_actino <- subset_taxa(armel_physeq, Phylum=="Actinobacteria")

plot_bar(armel_phy_bact_actino, fill = "Family")

**Comment by antagomir** [comment]
I am receiving this as a Github issue, and do not see any attachments. Could try to attach it here in the issue, or send email to my iki address?

**Comment by atangomo** [comment]
Dear Dr Leo,

This is attached the WinRAR reproducible data as well as the R script code.

Best regard

Armel Tangomo Ngnintedem

**Comment by antagomir** [comment]
Sorry, I do not reveive this by email if you reply through issues. Can you upload it directly on this github issues page and check that you see it here. Or send by email to my iki address

**Comment by atangomo** [comment]
[Demo_&_script_data.zip](https://github.com/microbiome/microbiome/files/4776081/Demo_._script_data.zip)

**Comment by atangomo** [comment]
Dear Leo,
 This is attached to the zip file demo and script data.
I was doing a mistake by sending it as a WinRAR file instead of sending it as Zip file.

Looking forward to hearing from you. 

Thank you

[Demo_&_script_data.zip](https://github.com/microbiome/microbiome/files/4776087/Demo_._script_data.zip)

**Comment by antagomir** [comment]
Thanks. Managed to download now. 

This was not directly executable as it had some comment lines that were not commented out, and setwd() command to folder that does not exist in my system. But those could be sorted out. The script contains a lot of material. Is this all necessary for replicating the bug? Could speed up response considerably, if you can provide a minimal example that has only those lines that are really needed for reproducing the (one single) bug, and remove all other lines.

**Comment by atangomo** [comment]
Dear Leo,

**First issue I wanted to plot more than 20 phyla relative abundance as a stake barplot. After the previous steps, I used this command to try to plot them.**

####  Composition plots

# First plot the real abundance

ps1.com.phyla <- microbiome::aggregate_taxa(ps1.com, "Phylum")

plot.composition.COuntAbun <- plot_composition(ps1.com.phyla) + theme(legend.position = "bottom") +
  scale_fill_brewer("Family", palette = "Paired") + theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Relative abundance") + guide_italics + theme(legend.title = element_text(size = 18))

plot.composition.COuntAbun

# Then use the transform function of the microbiome to convert plot real abundance into the relative abundance :

ps1.com.phyla.rel <- microbiome::transform(ps1.com.phyla, "compositional")

plot.composition.relAbun <- plot_composition(ps1.com.phyla.rel,
                                             sample.sort = "scientific_name",
                                             x.label = "env_material") 
plot.composition.relAbun <- plot.composition.relAbun + theme(legend.position = "bottom") 
plot.composition.relAbun <- plot.composition.relAbun + scale_fill_brewer("Phylum", palette = "Paired") + theme_bw() 
plot.composition.relAbun <- plot.composition.relAbun + theme(axis.text.x = element_text(angle = 90)) 
plot.composition.relAbun <- plot.composition.relAbun + ggtitle("Relative abundance") + guide_italics + theme(legend.title = element_text(size = 18))

print(plot.composition.relAbun)

**Bug message obtain**

**Warning message:
  In RColorBrewer::brewer.pal(n, pal) :
  n too large, allowed maximum for palette Paired is 12
Returning the palette you asked for with that many colours**



**The second issue is about the subsetting**

#subset to only the bacteria phylum

armel_phy_bact <- subset_taxa(armel_physeq, Phylum=="Bacteriodetes")

**Bug message**
**Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent**

Thanks for your help

**Comment by antagomir** [comment]
Is it possible to have this as executable source code file. Copypasting mixed text and code from here is not ideal for replication.

**Comment by atangomo** [comment]
I am not yet very strong on programming language yet but I will try to prepare an executable code file.

Thank you

**Comment by antagomir** [comment]
Thanks! It is enough to just remove (or uncomment) the extra comments from what you copypasted above, and attach it here as a text file. So that the file has only code that you can run with source("mycode.R") sort of command.

**Comment by atangomo** [comment]
Dear Leo,

This attaches the txt R code.

Thank you

[My_R_Code.txt](https://github.com/microbiome/microbiome/files/4777082/My_R_Code.txt)

**Comment by antagomir** [comment]
> source("My_R_Code.txt")
Error in tax_table(physeq, errorIfNULL) : object 'ps1.com' not found

**Comment by atangomo** [comment]
Please consider this one
[My_R_Code.txt](https://github.com/microbiome/microbiome/files/4777131/My_R_Code.txt)

**Comment by antagomir** [comment]
```
> source("My_R_Code.txt")
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './phyobjects/armel_physeq.rds', probable reason 'No such file or directory'

```

**Comment by antagomir** [comment]
Did you try to run this code in a fresh (empty) directory? I have the following files from the above zip

metadata.txt   
otu_matrix.csv          
taxonomy.csv
tree.nwk

**Comment by atangomo** [comment]
Yes, and it was perfectly working.

**Comment by atangomo** [comment]
Should I run it again in another fresh directory??

**Comment by antagomir** [comment]
Your code generates the above error message. I do not have that file (./phyobjects/armel_physeq.rds) and therefore the code fails.

**Comment by atangomo** [comment]
This is the entire code from the importation of phyloseq object to the specific area where I got the error
[Uploading My_R_Code.txt…]()

**Comment by atangomo** [comment]
[My_R_Code.txt](https://github.com/microbiome/microbiome/files/4777153/My_R_Code.txt)

**Comment by atangomo** [comment]
Please consider this code.

Thanks you

[My_R_Code.txt](https://github.com/microbiome/microbiome/files/4777164/My_R_Code.txt)

**Comment by antagomir** [comment]
Running this generates an error that indicates that a file called  phyobjects/armel_physeq.rds - I do not have such file and therefore it is impossible to run this code.

 cannot open compressed file './phyobjects/armel_physeq.rds', probable reason 'No such file or directory'

**Comment by atangomo** [comment]
Try this updated code
I have run it in a fresh directory
[My_R_Code (3).txt](https://github.com/microbiome/microbiome/files/4777199/My_R_Code.3.txt)

**Comment by antagomir** [comment]
I am sorry but there is still lot of code in this file that is completely irrelevant for producing the error. It would take time to read through it carefully in order to find the right parts of the code and ignore the rest. Can you clean up the code, and remove all parts that are not needed to reproduce the bug that you are reporting? A minimal example.

**Comment by atangomo** [comment]
Sorry, If I give you the direct code the way I did before, You will not reach the step of the error.

**Comment by antagomir** [comment]
Do you mean that it is not possible to provide a minimal example that reads the data, runs those commands (and _only_ those commands!) that are needed to reproduce the bug, and then fails with the error message? Why such minimal example could not be provided? I am mainly concerned that the latest R script contains a lot of unnecessary lines of code, and this is making it slower to go through.

**Comment by atangomo** [comment]
Dear Leo, please check this shortcode R version.
[My_R_Code_updated.txt](https://github.com/microbiome/microbiome/files/4777304/My_R_Code_updated.txt)

**Comment by antagomir** [comment]
Thanks. 

Could you provide the phyloseq object as an RData file? Then I can skip all the data preparation steps in the beginning of this code.

Does the error occur already on the first line of the plot_composition function? In yes, can you remove all later subsequent lines because these are not needed to reproduce the bug.

**Comment by atangomo** [comment]
This is the zip file containing both the code and phyloseq object
Thanks
[R_code_phyloseq_object.zip](https://github.com/microbiome/microbiome/files/4777337/R_code_phyloseq_object.zip)

**Comment by antagomir** [comment]
Thanks. This R code does not have any data import. On the first line it calls "ps1.com" and second line it calls "ps1.com.phyla". Are these expected to be in the file "phyobjects/armel_physeq.rds" that is included in this zip? Could you add a command in the R file that reads this file so that the objects from it can then be used in the code. In the same way that you had already in your earlier codes? 

I just need one simple zip that I can uncompress, and then run the R code so that it automatically reads data from the file, runs the lines that reproduce the bug, and then fails with error message. If you test your code by uncompressing it in a new directory before sending here, you can see if it runs through successfully. If not, I am sure you will be able to fix it.

There are also lines where I am not sure if they are needed to reproduce the bug. For instance the first plotting command "plot.composition.COuntAbun", if you remove that is the bug still occurring? If yes, then it is not necessary to have it and it can be removed. Can you remove all parts that are not absolutely necessary for reproducing the bug?

**Comment by atangomo** [comment]
Thanks Dear Leo,

This the updated script and phyobjects following your instruction.

[armel_script.zip](https://github.com/microbiome/microbiome/files/4779954/armel_script.zip)

**Comment by antagomir** [comment]
The plotting command uses "ps1.com.phyla.rel". Can you send this as RData object?

Does the error occur already if you run this line? If yes, there is still many lines in the code that are not needed to reproduce the bug.

```
plot_composition(ps1.com.phyla.rel,
                                             sample.sort = "scientific_name",
                                             x.label = "env_material")

```

**Comment by atangomo** [comment]
I thought the RData object was already sent in the previous zip document?

**Comment by atangomo** [comment]
I thought I have already provided the demo data as well as the command that can be used to reproduce the bug. 
I will be glad if you can skip those unwanted lines and help me to solve those specific bugs issues.

**Comment by antagomir** [comment]
The zip contains "armel_physeq.rds" and this gives the object "ps1". However this object is manipulated in the code further to get "ps1.com.phyla.rel" before getting to the actual bug that you would like us to help to solve. The problem is that for some reason, some of those manipulations fail at my end, and I never get to "ps1.com.phyla.rel" object. I should debug those parts first if you do not provide that object directly. And I do not have time to do that extra debugging right now. If you prefer fast responses, this can be facilitated by providing the actual data object that reproduces the bug, i.e. "ps1.com.phyla.rel". 

I can remove the unwanted lines but ideally we could just focus on fixing the bug instead. That's the idea of minimal examples.

**Comment by atangomo** [comment]
Please in case you have time, just help Me. I will be patient!!! Thank you.

**Comment by antagomir** [comment]
Thanks. Without having the object "ps1.com.phyla.rel" I cannot help. This object is not in the attached zip files.

**Comment by atangomo** [comment]
Ok, Thanks
