### ISSUE TITLE
F/b ratio and bfratio() function

### ISSUE THREAD

**Issue by tortaho** [microbiome/microbiome#142]
I am trying to calculate the f/b ratio of my 16s dataset for my analyses. 

I noticed that there is a bfratio() function and tried it out, however, I run into this error message: 

>            Error in abundances(a)["Bacteroidetes", ] : subscript out of bounds

From what I understand, it has to do with the names of my variables in the phyloseq object. However, I am not too familiar with these objects and don't know how to alter them easily. 

Instead, I was wondering how the bfratio() is calculated so that I can do it manually for the f/b ratio. Is it simply the abundance of one phyla over the other? Or is there a transformation involved?

Thanks!

**Comment by antagomir** [comment]
Your abundance matrix needs to aggregated to Phylum level and it needs to contain that group. 

Yes if is just b/f ratio.
