### ISSUE TITLE
Exporting relative abundance data into excel sheet

### ISSUE THREAD

**Issue by srisvs33** [microbiome/microbiome#144]
Dear all

Here is the code, that i have used to plot relative abundance bar graph. Now i would like to export the plotted relative abundance value with taxonomy into tabular format either in CSV/Excel. Can some one guide me , how to do that. 
I have tried to use,  write.table command, but it throw an error. 

**Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘c("gg", "ggplot")’ to a data.frame**

code used to generate relative abundance top 10 phylum

**Alpha <- aggregate_top_taxa(physeq_ra, top = 10, 'Phylum')

Beta <- plot_composition(Alpha, sample.sort = NULL,
                          otu.sort = "abundance",
                          x.label = "samples", 
                          plot.type = "barplot", 
                          verbose = FALSE) +  theme_classic() + scale_fill_brewer("Phylum", palette = "Paired")** 

Many thanks in advance

regards
Venkat

**Comment by microsud** [comment]
Thanks for writing. You can use the `Alpha` object you created and follow the section _Merging operations_ in  [this tutorial](https://microbiome.github.io/tutorials/Preprocessing.html), where we show how to Join otu/asv table and taxonomy in one data frame. After joining the taxonomy and asv data you can use write.table. 
Hope this helps. 

Best wishes,
Sudarshan

P.S. If it solves your query, please close this issue.

**Comment by srisvs33** [comment]
Hi Sudarshan

Thanks a lot for quick response. It solved my issue.

regards
Venkat
