### ISSUE TITLE
extract peerj32 data as a dataframe

### ISSUE THREAD

**Issue by khemlalnirmalkar** [microbiome/microbiome#145]
Hi,
I am trying to make a heatmap with a correlation using the microbiome package but i am not able to understand the sample data from peerj32 and failing to arrange my own data for the analysis.

Please can you share the peerj32 sample data as data.frame or way to extract it?

Thanks

**Comment by antagomir** [comment]
The peerj32 object is a list with four elements as mentioned in the documentation: help(peerj32)

        • lipids: Quantification of 389 blood serum lipids across 44
          samples -> matrix

        • microbes: Quantification of 130 genus-like taxa across 44
          samples  -> matrix

        • meta: Sample metadata including time point, sex, subjectID,
          sampleID and treatment group (probiotic LGG / Placebo) -> data.frame

        • phyloseq The microbiome data set converted into a
          ‘phyloseq-class’ object. -> phyloseq object constructed from the above 'microbes' and 'meta'

Does this help?

**Comment by khemlalnirmalkar** [comment]
Thanks for the quick response, this was helpful, Appreciated 
My R skills is limited,
2-more questions:
a) Please may i know, once i will have my own data like lipids, microbes and meta, how can i add them together like peerj32?
b) Microbes from peerj32, doesnt look like relative abundance. Do i need to use absolute abundance? or relative abundance will also fine?
c) For metabolites, do i need to use normalized data? I already have Z-score normalized metabolites data, but i saw in the tutorial, before heatmap step, (phyloseq object)  everything converts into z-score. what will be the best way to use my metabolites data?
Thanks,

**Comment by antagomir** [comment]
a) If you have three data objects you make them a list:
`peerj32 <- list(lipids = lipids, microbes = microbes, meta = meta)`

b) The microbial matrix is HITChip (phylogenetic microarray for 16S profiling) absolute values. You can calculate relative abundances from this if you need to.

c) For metabolites additional normalization in this case not usually done. All relevant info on that is described in the Methods section of the manuscript and we have not done additional normalization for the metabolite data. For visualization purposes we sometimes use additional tricks like z score but that is mainly for visualization purposes, to highlight specific patterns and compare across samples.

**Comment by khemlalnirmalkar** [comment]
Thank you so much,
