### ISSUE TITLE
Chao1 for alpha() and estimate_richness differ

### ISSUE THREAD

**Issue by biobee** [microbiome/microbiome#150]
Hi Leo,

Not sure why, but Chao1 in microbiome::alpha() and phyloseq::estimate_richness return different results, using: microbiome_1.8.0 and  phyloseq_1.30.0 and same pseq object

> range(microbiome::richness(pseq, "chao1"))
[1]  26.5000 182.4474
> range(microbiome::alpha(pseq, "chao1"))
[1]  26.5000 182.4474

> range(phyloseq::estimate_richness(pseq, measures="Chao1")$Chao1)
[1]  19.00 177.75

[1]   3.656573 177.750000

**Comment by biobee** [comment]
Microbiome and mothur/vegan/phyloseq/PAST use a different Chao1 equation. The latter use a bias-corrected one.  Microbiome switches between two equations. 


Chao1 microbiome: r <- s0+s1^2/(s2*2) or r <- s0+s1*(s1-1)/((s2+1)*2) (latter is bias-corrected)

Chao1 phyloseq/vegan/mothur: r <- s0+s1*(s1-1)/((s2+1)*2) (bias-corrected)

-vegan in estimateR, returning a value per sample., the bias-corrected version above is used
-vegan in specpool uses the bias-corrected one when there are no doubletons (s2==0)
-switch in microbiome is on:  if(s1-s2)^2==(s1+s2)^2), see https://github.com/microbiome/microbiome/blob/master/R/richness.R

**Comment by antagomir** [comment]
Thanks! Now using the bias corrected version always in v. 1.13.4
