### ISSUE TITLE
Error in UseMethod("droplevels") when using plot_composition

### ISSUE THREAD

**Issue by dvuono** [microbiome/microbiome#151]
I updated from microbiome version 1.8.0 to 1.12.0 and now have this issue when trying to plot_composition:

Error in UseMethod("droplevels") : no applicable method for 'droplevels' applied to an object of class "character"

I noticed that the output from summary(tax_tables(my_phyloseq_object)) gives:

 Kingdom             Phylum             Class              Order              Family             Genus          
 Length:469         Length:469         Length:469         Length:469         Length:469         Length:469        
 Class :character   Class :character   Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
   Species         
 Length:469        
 Class :character  
 Mode  :character  

when it used to list the actual names of the taxonomic levels. I see that "droplevels" is supposed to work on factors but can't seem to figure out how to convert the taxa names from "character" to "factor" either.  Help appreciated.

**Comment by antagomir** [comment]
Can you try the most current devel version (1.13.4)?

`devtools::install_github("microbiome/microbiome")`

If the problem persists, then it would help if you can provide a reproducible example either with one of our demo data sets, or by sharing a phyloseq object as RData (or Rds) file

**Comment by dvuono** [comment]
I think I figured it out. The issue is not with the tax table. It's with the metadata columns, and it occurs with both v1.12.0 and v1.13.4. I tested this on the atlas1006 dataset. The meta(atlas1006) function shows many of the columns as factors, such as "sex", "nationality", "bmi_group", etc... but one column called "samples" is a character. If you try:

plot_composition(fl1.com.phylum.abs, average_by = "sample", otu.sort = "abundance")

The "droplevels" error occurs, whereas if you averaged by "sex" or one of the other factors, no error occurs.

See if you can reproduce this, it might also be my environment since I updated all of my R stuff.

**Comment by antagomir** [comment]
Samples are unique, it is not possible to average them in the first place. So there is no point in running this for samples. 

In some cases, the character fields might not be unique, and averaging makes sense. We could fix that case by converting the average_by variable into a factor within the function, I added this now to new commit, version 1.13.5 but haven't tested. Let us know if it works or fails.

**Comment by dvuono** [comment]
The point of the example is to show that trying average_by to any column within the metadata file that is a character, does not work for plot_composition. When I modified my metadata file to have the specific columns I needed as factors, the average_by option works. So the point is that this used to work for characters, but now doesn't. Converting the variable into a factor within the function should solve this issue. Thank you for your help.

**Comment by antagomir** [comment]
Hi - I have done exactly that change in 1.13.5 but did not have time to test yet. Does it work now?

**Comment by dvuono** [comment]
Just tested it and it works. Thank you.

**Comment by antagomir** [comment]
Excellent :-)
