### ISSUE TITLE
conditionally rare taxa

### ISSUE THREAD

**Issue by ARBramucci** [microbiome/microbiome#152]
Is there a way to identify and pull out all conditionally rare taxa? So basically the reverse of the core code, but allowing the user to pull out anything that is never >0.001 relative abundance in any of the samples?

Also I am attempting to use the aggregate to family code, but I am not sure it is doing what I think it is doing. My understanding is that by running the following:
`physeq.rel.fam <- aggregate_taxa(physeq.rel, "Family")`

my new physeq.rel.fam should have added together all genera species and ASVs that are within a given family together into a new table, is that what is going on? So that when I run the core code again on this physeq.rel.fam I should get all families that are found in 90% of the samples?

**Comment by antagomir** [comment]
Did you check the functions "rare" and "rare_members"? 

The latter question, answer is yes. If you find discrepancies, kindly report. It should work as you describe.

**Comment by ARBramucci** [comment]
Thanks so much I understand it better now!
