### ISSUE TITLE
Understanding coefficients permanova group comparison

### ISSUE THREAD

**Issue by elcega** [microbiome/microbiome#154]
Hi, 
I am following one of the tutorials:
https://microbiome.github.io/MiaBook/microbiome-diversity.html

When running
`coef <- coefficients(permanova)["group1",]`
What does "group1" or "group2" mean? - 
which comparison is it using?

In my case I have three groups, and it allows me to run that coefficients function with group1 and group2, 
- how do I know which groups is it comparing?
- Can I manually select which comparisons I am interested in? (ie: G1 vs G3; G2 vs G3)

The default data also has three groups so I would imagine is a similar comparison?
```
Pairwise comparisons:
(Observed p-value below diagonal, permuted p-value above diagonal)
           G1        G2   G3
G1            5.6700e-01 0.024
G2 5.7749e-01            0.001
G3 1.8579e-02 7.9566e-05 
```
Thanks,

**Comment by antagomir** [comment]
The "group1" refers to the group name. In your data is something else "G1" so use that.
