### ISSUE TITLE
boxplot_abundance() doesn't recognize x value

### ISSUE THREAD

**Issue by brynaR** [microbiome/microbiome#157]
I am trying to use boxplot_abundance to graph the abundance of individual organisms in my study groups. I am trying to run: boxplot_abundance(wfcss, x="Sex",y="Akkermansia")+scale_y_log10() 
where wfcss is my phyloseq object and "Sex" is the column for sex. I get the error:
Error in `[.data.frame`(data.frame(x), i, j, drop = FALSE) : undefined columns selected

It does this regardless of what column I try to use. I have checked my column names and that the capitalization is correct.

When I intentionally use improper capitalization or use a column name that does not exist in my data (i.e. "sex" or "elephant"), I get the following error:
Error in `$<-.data.frame`(S3Part(x, TRUE), name, value) : replacement has 0 rows, data has 143

I'm not sure what else to try to fix this. Any advice is much appreciated.
Thank you

**Comment by antagomir** [comment]
Thanks!

Are you able to provide a reproducible example by using one of the demo data sets in the R pkg? Otherwise, could you share/send example data and code reproducing the bug from that data. Then it will be easier to debug and help.

**Comment by antagomir** [comment]
Your data does not have taxonomic group with name "Akkermansia" which you can see with 
`taxa(x)`.. these are more refined groups, not genera.

You do have Akkermansia in the taxonomic table (`tax_table(x)`) and you can aggregate your abundances to this genus level with
`x2 <- aggregate_taxa(x, "Genus")`.

It seems that plotting for this object is possible.

Next time, also include the code to read the data and libraries and execute commands, this will speed up testing.
