### ISSUE TITLE
Error in access(object, "sam_data", errorIfNULL) :    sam_data slot is empty

### ISSUE THREAD

**Issue by mr2raccoon** [microbiome/microbiome#158]
Hey,

I tried the general summary function `summarize_phyloseq(physeq_nano) ` and 
got the following error message: `summarize_phyloseq(physeq_nano) `   

Another issue: 
`reads_sample <-readcount(physeq_nano)`    &
`samplesum <- sample_sums(physeq_nano)`

returns the same values for me. Both functions return the number of reads per sample for my data.
`sample_sum()` does not return the number of obs OTU per sample.

Any suggestions?

**Comment by antagomir** [comment]
The `readcount` and `sample_sums` are indeed both giving the number of reads per sample. 

For number of observed OTUs you should use microbiome::richness(x, index = "observed")

@microsud may like to comment on `summarize_phyloseq` but I do not see the actual error message above.

**Comment by microsud** [comment]
Yes, I also don't see the error msg. @mr2raccoon Could you elaborate on it?

**Comment by mr2raccoon** [comment]
Sorry the problem was that I had trouble loading my sample data into the "phyloseq object". I could solve that issue yesterday. One more question though:

Is it possible to "summarize-phyloseq" per sample so that I can see the number of singletons per sample etc. Thanks for the quick reply! I love your package!

**Comment by microsud** [comment]
Great! For singletons, you can try the following code.

```
library(microbiome)
data("dietswap") # example data
ps <- dietswap
otu <- abundances(ps) # rows are OTUs and columns are Samples

# for each column count how many equal to 1 (singletons)
singletons_per_sample <- apply(otu, 2, function(x) length(which(x == 1)))
# add it to sample_data i.e. phyloseq::sample_data()
sample_data(ps)$Singletons <- singletons_per_sample
```
For your own data, make sure to check at least one sample to see if the calculation of singleton is as expected. 

If these have resolved your queries, please close this issue. 

Best wishes,
Sudarshan

**Comment by mr2raccoon** [comment]
Thanks a lot! Great advice!
