### ISSUE TITLE
microbiome::transform with "hellinger" not respecting taxa_are_rows of phyloseq object

### ISSUE THREAD

**Issue by didillysquat** [microbiome/microbiome#159]
Hi All,

Thank you for your efforts.

I'm getting some unexpected behaviour when using the `transform` function.

See below. I'm getting the exact same results when using `transform` whether the phyloseq object has `taxa_are_rows` as `TRUE` or `FALSE`. The default value for `target` is "OTU". I would therefore expect that the standardisation would be conducted along the opposite axis (i.e. rows vs columns) in each case, because the OTUs are represented by opposite axes in each case.  It seems that `transform` is not passing the correct value to `MARGIN` in the underlying `vegan::decostand` call.

Am I misunderstanding something?

Thanks a bunch.

```
> t.taxa.in.rows = phyloseq(otu_table(t, taxa_are_rows = TRUE))
> t.taxa.in.rows
OTU Table:          [6 taxa and 6 samples]
                     taxa are rows
       a  b  c  d  e f
one    1  1  1  3  3 1
two    2  2  4  6  6 0
three 10 10 20 30 30 0
four   3  3  2  1  1 0
five   0  0  0  0  1 0
six    0  0  0  0 20 0
> t.taxa.in.cols = phyloseq(otu_table(t, taxa_are_rows = FALSE))
> t.taxa.in.cols
OTU Table:          [6 taxa and 6 samples]
                     taxa are columns
       a  b  c  d  e f
one    1  1  1  3  3 1
two    2  2  4  6  6 0
three 10 10 20 30 30 0
four   3  3  2  1  1 0
five   0  0  0  0  1 0
six    0  0  0  0 20 0
> microbiome::transform(t.taxa.in.rows, transform="hellinger")
              a         b         c         d         e f
one   0.2500000 0.2500000 0.1924501 0.2738613 0.2217664 1
two   0.3535534 0.3535534 0.3849002 0.3872983 0.3136250 0
three 0.7905694 0.7905694 0.8606630 0.8660254 0.7012869 0
four  0.4330127 0.4330127 0.2721655 0.1581139 0.1280369 0
five  0.0000000 0.0000000 0.0000000 0.0000000 0.1280369 0
six   0.0000000 0.0000000 0.0000000 0.0000000 0.5725983 0
attr(,"decostand")
[1] "hellinger"
> microbiome::transform(t.taxa.in.cols, transform="hellinger")
              a         b         c         d         e f
one   0.2500000 0.2500000 0.1924501 0.2738613 0.2217664 1
two   0.3535534 0.3535534 0.3849002 0.3872983 0.3136250 0
three 0.7905694 0.7905694 0.8606630 0.8660254 0.7012869 0
four  0.4330127 0.4330127 0.2721655 0.1581139 0.1280369 0
five  0.0000000 0.0000000 0.0000000 0.0000000 0.1280369 0
six   0.0000000 0.0000000 0.0000000 0.0000000 0.5725983 0
attr(,"decostand")
[1] "hellinger"
```

**Comment by antagomir** [comment]
Hi - I agree that this is somewhat confusing. 

Only the Z transformation is routinely done also from target = "sample" and I think we had just switched off that option for most other transformations. In order to avoid confusion it would be perhaps most clear to split these into otu- and sample-specific transformation functions.

**Comment by didillysquat** [comment]
@antagomir 
Thanks for your rapid reply.

I'm sorry to say that I'm still confused.

Perhaps I'm misunderstanding the meaning of `target`. I thought that it would refer to the axis by which to standardise.
I.e. by changing target between "sample" or "OTU" would cause the values to be divided by either the row totals, or the column totals, depending on which orientation the phyloseq object was in (i.e. `taxa_are_rows` = TRUE|FALSE).

But if I understand you, you are saying that the below is the correct expected behaviour for hellinger transform? And if so, then how would I get the standardization to be done across 'the other' axis. I.e. in this case, how could I get the 'hellinger' to be conducted with MARGIN=1 as in `vegan::decostand(t, method="hellinger", MARGIN=1)` other than by transposing my ordinal matrix that I fed into the phyloseq object?

Even more confusingly, changing `target` does have an effect when using `transform="compositional"` (see below), but it still doesn't respect the phyloseq `taxa_are_rows` property at all (see below).

Thanks.

```
> microbiome::transform(t.taxa.in.rows, transform="hellinger", target="sample")
              a         b         c         d         e f
one   0.2500000 0.2500000 0.1924501 0.2738613 0.2217664 1
two   0.3535534 0.3535534 0.3849002 0.3872983 0.3136250 0
three 0.7905694 0.7905694 0.8606630 0.8660254 0.7012869 0
four  0.4330127 0.4330127 0.2721655 0.1581139 0.1280369 0
five  0.0000000 0.0000000 0.0000000 0.0000000 0.1280369 0
six   0.0000000 0.0000000 0.0000000 0.0000000 0.5725983 0
attr(,"decostand")
[1] "hellinger"
> microbiome::transform(t.taxa.in.cols, transform="hellinger", target="sample")
              a         b         c         d         e f
one   0.2500000 0.2500000 0.1924501 0.2738613 0.2217664 1
two   0.3535534 0.3535534 0.3849002 0.3872983 0.3136250 0
three 0.7905694 0.7905694 0.8606630 0.8660254 0.7012869 0
four  0.4330127 0.4330127 0.2721655 0.1581139 0.1280369 0
five  0.0000000 0.0000000 0.0000000 0.0000000 0.1280369 0
six   0.0000000 0.0000000 0.0000000 0.0000000 0.5725983 0
attr(,"decostand")
[1] "hellinger"
> microbiome::transform(t.taxa.in.cols, transform="hellinger", target="OTU")
              a         b         c         d         e f
one   0.2500000 0.2500000 0.1924501 0.2738613 0.2217664 1
two   0.3535534 0.3535534 0.3849002 0.3872983 0.3136250 0
three 0.7905694 0.7905694 0.8606630 0.8660254 0.7012869 0
four  0.4330127 0.4330127 0.2721655 0.1581139 0.1280369 0
five  0.0000000 0.0000000 0.0000000 0.0000000 0.1280369 0
six   0.0000000 0.0000000 0.0000000 0.0000000 0.5725983 0
attr(,"decostand")
[1] "hellinger"
> microbiome::transform(t.taxa.in.cols, transform="compositional", target="OTU")
           a      b          c     d          e f
one   0.0625 0.0625 0.03703704 0.075 0.04918033 1
two   0.1250 0.1250 0.14814815 0.150 0.09836066 0
three 0.6250 0.6250 0.74074074 0.750 0.49180328 0
four  0.1875 0.1875 0.07407407 0.025 0.01639344 0
five  0.0000 0.0000 0.00000000 0.000 0.01639344 0
six   0.0000 0.0000 0.00000000 0.000 0.32786885 0
> microbiome::transform(t.taxa.in.rows, transform="compositional", target="OTU")
           a      b          c     d          e f
one   0.0625 0.0625 0.03703704 0.075 0.04918033 1
two   0.1250 0.1250 0.14814815 0.150 0.09836066 0
three 0.6250 0.6250 0.74074074 0.750 0.49180328 0
four  0.1875 0.1875 0.07407407 0.025 0.01639344 0
five  0.0000 0.0000 0.00000000 0.000 0.01639344 0
six   0.0000 0.0000 0.00000000 0.000 0.32786885 0
> microbiome::transform(t.taxa.in.rows, transform="compositional", target="sample")
  one two three four five six
a 0.1 0.1   0.1  0.3    0   0
b 0.1 0.1   0.1  0.3    0   0
c 0.1 0.2   0.2  0.2    0   0
d 0.3 0.3   0.3  0.1    0   0
e 0.3 0.3   0.3  0.1    1   1
f 0.1 0.0   0.0  0.0    0   0
```

**Comment by microsud** [comment]
@antagomir does this have to do with abundances() returning taxa as rows within transform ()?

**Comment by antagomir** [comment]
Ok. I fixed the implementation and it should now work more logically and for all options. Unit tests also go through.

But would be good to know if something is not as expected from your point of view.

**Comment by didillysquat** [comment]
@antagomir 
Thanks for your efforts.
I can confirm that the `transform` method is now changing with respect to the `taxa_are_rows` argument of the `otu_table` object of the `phyloseq` object.

I can also confirm that the `transform` method is now changing with respect to the `target` argument of the `transform` method.

However, the axis along which the transform is acting is the opposite to what I would expect. BUT, I think this is my misunderstand of what the `target` means:

When the target is "sample", I would expect the relative proportions to be standardised so that each **sample** sums to 1, **not** each OTU (current behaviour is shown below). Can you confirm that I've got this the wrong way around in my head. 

Certainly, the default behaviour (`target="OTU"`), is what I would expect in most use cases (i.e. sample rows or columns summing to 1). So I'm fairly sure that this is purely a misunderstanding of the `target` argument definition by me.

```
> t.otu.table.taxa.in.cols
OTU Table:          [6 taxa and 6 samples]
                     taxa are columns
             OTUa OTUb OTUc OUTd OTUe OTUf
sample_one      1    1    1    3    3    1
sample_two      2    2    4    6    6    0
sample_three   10   10   20   30   30    0
sample_four     3    3    2    1    1    0
sample_five     0    0    0    0    1    0
sample_six      0    0    0    0   20    0
> microbiome::transform(t.otu.table.taxa.in.cols, transform='compositional')
OTU Table:          [6 taxa and 6 samples]
                     taxa are columns
             OTUa OTUb OTUc OUTd OTUe OTUf
sample_one    0.1  0.1  0.1  0.3  0.3  0.1
sample_two    0.1  0.1  0.2  0.3  0.3  0.0
sample_three  0.1  0.1  0.2  0.3  0.3  0.0
sample_four   0.3  0.3  0.2  0.1  0.1  0.0
sample_five   0.0  0.0  0.0  0.0  1.0  0.0
sample_six    0.0  0.0  0.0  0.0  1.0  0.0
> microbiome::transform(t.otu.table.taxa.in.cols, transform='compositional', target='sample')
OTU Table:          [6 taxa and 6 samples]
                     taxa are columns
               OTUa   OTUb       OTUc  OUTd       OTUe OTUf
sample_one   0.0625 0.0625 0.03703704 0.075 0.04918033    1
sample_two   0.1250 0.1250 0.14814815 0.150 0.09836066    0
sample_three 0.6250 0.6250 0.74074074 0.750 0.49180328    0
sample_four  0.1875 0.1875 0.07407407 0.025 0.01639344    0
sample_five  0.0000 0.0000 0.00000000 0.000 0.01639344    0
sample_six   0.0000 0.0000 0.00000000 0.000 0.32786885    0
Warning message:
In microbiome::transform(t.otu.table.taxa.in.cols, transform = "compositional",  :
  compositional transformation is not typically 
        used and not recommended for samples. Consider using target = OTU.
```

**Comment by antagomir** [comment]
Your understanding is correct. I also agree that the naming is somewhat confusing. But this is not really intended to be used for sample-wise transformations. This is why I was thinking that it might be better to separate the taxon- and sample specific transformations into distinct functions. We cannot really change the naming scheme because this could potentially break the workflows for a number of users.

**Comment by didillysquat** [comment]
@antagomir 
I completely understand the need to keep this back compatible for sake of existing pipelines.

At the end of the day, the transformations now react to the arguments in the way I would expect them to, and the default behaviour is going to be appropriate in most use cases.

Thanks again for your efforts!

**Comment by antagomir** [comment]
Thanks for the feedback, always welcome.
