### ISSUE TITLE
format_to_besthit of microbiome does not include the phy_tree in its result

### ISSUE THREAD

**Issue by tcrispino13** [microbiome/microbiome#160]
Is there a way to include the phy_tree in the phyloseq object after using the format_to_besthit function? Ive been following this commands and I need to measure the unifrac distances based on the phylogenetic tree but after using the format_to_besthit, it turns out the phy_tree was not included. 

ps2 <- tax_glom(ps, "genus")
ps2f <- format_to_besthit(ps)
orddi <- ordinate(ps2f, method = "PCoA", distance = "unifrac", weighted= FALSE)
Error in access(physeq, "phy_tree", errorIfNULL) : 
  phy_tree slot is empty.

**Comment by antagomir** [comment]
I think this is from @microsud R pkg [microbiomeutilities](https://github.com/microsud/microbiomeutilities) and the issue would belong there.

**Comment by tcrispino13** [comment]
Thanks for this response! Will send the issue to microbiomeutilities.
