### ISSUE TITLE
error in plot_composition with plot.type = "heatmap"

### ISSUE THREAD

**Issue by marcinschmidt** [microbiome/microbiome#163]
I am trying to run the `plot_composition` function with `plot.type = "heatmap"` on a phyloseq `microbiome::transform(ps, "compositional")`, using the microbiome package version 1.13.8. 
```
ps.rel <- microbiome::transform(ps, "compositional")
p <- plot_composition(ps.rel, plot.type = "heatmap", sample.sort = "neatmap", otu.sort = "neatmap")
```
and get an error
```
Error in hclust(as.dist(1 - cor(mat, use = "pairwise.complete.obs"))) : 
  NA/NaN/Inf in foreign function call (arg 10)
In addition: Warning message:
In cor(mat, use = "pairwise.complete.obs") : the standard deviation is zero
```
however, for `plot.type = "barplot"` I get a nice plot

Can anyone help me with that?

Best regards,
Marcin

**Comment by marcinschmidt** [comment]
should be `ps.rel <- microbiome::transform(ps, "log10")` transformed

**Comment by antagomir** [comment]
You could also check clr transformation.
