### ISSUE TITLE
a bug in integer check in microbiome::transform?

### ISSUE THREAD

**Issue by huckbuc** [microbiome/microbiome#164]
Hi,

This is my first time ever using github (though I have lots of R experience).  Hope I'm not missing something.

I believe there is a bug in the integer check of the OTU abundances inside the function `transform()`.  The condition is:

`if (!all(sample(round(prod(dim(abundances(x)))/10)))%%1 == 0)`

I cannot see how the `sample`, `prod`, and `dim` functions are relevant, and why one needs both the modulo operator and the rounding.  From a small test I ran, the condition indeed doesn't detect non-integer values in the `otu_table` slot.

Shouldn't the condition simply be `if(!all(abundances(y)%%1 == 0))` ?

**Comment by antagomir** [comment]
Yes I guess so. There is some historical reason behind this. 

Would you be willing to try and make a pull request (PR) to change this?

**Comment by huckbuc** [comment]
Thanks for the quick reply.  As I wrote, I am new to github, and have only a vague idea what a pull request is.  I am also too busy these days to dive into these things, so I think I'll pass.  Thanks again, though!

**Comment by antagomir** [comment]
Fixing now, thanks.
