### ISSUE TITLE
linear model and microbiome compositional data

### ISSUE THREAD

**Issue by WisamR** [microbiome/microbiome#165]
Hi,
following the microbiome tutorial page, I stopped in:
https://microbiome.github.io/tutorials/Mixedmodels.html
As microbiome data are compositional according to 
https://www.frontiersin.org/articles/10.3389/fmicb.2017.02224/full
My question is:
As 'signal' in the code is the read counts from OTU table for 'Akkermansia', does the linear model there is appropriate when the data are compositional? I mean, is it Ok to apply a linear model to microbial data without any preprocessing to overcome the compositional property of the data?

Best regards

Wisam

**Comment by antagomir** [comment]
This is a vast question. In general, generalized linear models (negative binomial etc) are more appropriate for count data and then library size can be included as a variable, or one can do variance stabilizing transformations, see e.g. [McMurdie & Holmes (2014)](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531). If you do linear model then it could help to do log-ratio transformation (e.g. clr) before such analyses as those are designed to remove compositionality bias. But such transformations require pseudocount and do not account for variations in library sizes. 

We are now working on an updated framework, a draft online manual is building up [here](microbiome.github.io/oma/)

**Comment by WisamR** [comment]
Thank you.
