### ISSUE TITLE
stacked bar chart and loess ggplot for top 20 using aggregate_top_taxa?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#167]
I am trying to ggplot relative abundance as  Stacked Bar Chart for GENUS level 
```
ggplot(ps_genus, aes(x = Sample, y = Abundance, fill = Genus)) + 
  geom_bar(stat = "identity", width=1) +
  facet_wrap(phase~part*treatment, scales = "free_x", nrow = 6, ncol=4) +
  theme(axis.text.x = element_blank()) +
  theme(axis.title.x = element_blank()) +
  labs(title = "Relative Abundance of Genus")
```
`ggsave("figures/ra.genus.tiff", height = 5, width = 15, scale = 1.2)`
![image](https://user-images.githubusercontent.com/68851733/134630937-bdd6ab80-bcf4-4953-b73d-7eae808bfeb1.png)

# and Loess smoother (at Genus level):

```
ggplot(ps_genus, aes(x = treatment, y = Abundance, color = Genus, group = Genus)) +
  stat_smooth(method = "loess") +
  facet_grid(~phase*part) +
  xlab("Phase") +
  ylab("Relative Abundance") +
  labs(title = "Relative Abundance") +
  geom_point(size = 1.25, alpha = 0.4)
```

`ggsave("figures/ra.loess.Genus.allPhasesG.tiff", height = 5, width = 15, scale = 1.2)
`
ps_genus was created from the filtered phyloseq object as follow:

`ps.ra <- transform_sample_counts(ps.prev, function(ASV) ASV/sum(ASV))`

> ps.ra

> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 180 taxa and 166 samples ]
> sample_data() Sample Data:       [ 166 samples by 7 sample variables ]
> tax_table()   Taxonomy Table:    [ 180 taxa by 7 taxonomic ranks ]
> phy_tree()    Phylogenetic Tree: [ 180 tips and 179 internal nodes ]
> refseq()      DNAStringSet:      [ 180 reference sequences 

```
ps_genus <- ps.ra %>%
  tax_glom(taxrank = "Genus") %>%
  psmelt()
```

AND to proceed with the idea that Genus members are many and difficult to view as you can see in the fig so I chose to make top 20:

# I first removed the phy_tree and refseq
```
ps.ra1 <- ps.ra
ps.ra1@phy_tree <- NULL
ps.ra1@refseq <- NULL
```

# Second merge at the family level
`ps_family_top20 <- microbiome::aggregate_top_taxa(ps1.com, "Family", top = 20)`

> Warning message:
>   'microbiome::aggregate_top_taxa' is deprecated.
> Use 'aggregate_rare' instead.
> See help("Deprecated") and help("The microbiome::aggregate_top_taxa function is deprecated.-deprecated").
> 
> aggregate_top_taxa' is deprecated.
> Use 'aggregate_rare' instead.

aggregate_rare don't have the option of top 20 or 10. 
Could you please advise?

The version I am using of microbiome is 1.12.0 which I need to use at the moment.

Thanks

**Comment by antagomir** [comment]
Kindly update to the latest development version 1.13.13  with `devtools::install_github("microbiome/microbiome")` and then report if the problem persists.

**Comment by marwa38** [comment]
Thanks for your reply Leo @antagomir 
I just installed microbiome in Rstudio using this command
`devtools::install_github("microbiome/microbiome")`
 and checked the package and found it to be 1.14
 the error still persists

**Comment by antagomir** [comment]
Ok. Does the problem occur also with our demonstration data sets? Is it possible to have one script that we can directly copypaste and generates the error? This could speed up debugging.

**Comment by marwa38** [comment]
Hi Leo @antagomir
I tried and used the following rather than index = all
`alpha.microbiome.unrare <- alpha(ps.prev, index = c("observed", "diversity_shannon"))`
and it worked 
how can I know which ones are not working so that I select the others for downstream analysis?

**Comment by antagomir** [comment]
For me the following works without problem:

```
library(microbiome)
data(dietswap)
alpha(dietswap, index="all")
```

The available index names are available through the specific richness, evenness, diversity etc functions. See `help(microbiome::alpha)`

**Comment by marwa38** [comment]
Thanks so much Leo @antagomir 

it worked when I just chose some of the alpha diversity indices (for alpha) and also for aggregate_taxa although it is still giving the warning message (should I worry about that?)

> Warning message:
> 'microbiome::aggregate_top_taxa' is deprecated.
> Use 'aggregate_rare' instead.
> See help("Deprecated") and help("The microbiome::aggregate_top_taxa function is deprecated.-deprecated").
> 
> aggregate_top_taxa' is deprecated.
> Use 'aggregate_rare' instead.
*just to let you know that I am using the package in conda environment and I updated it to the latest version 

> > sessionInfo()
> R version 4.1.0 (2021-05-18)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.3 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /home/r01mt19/.conda/envs/updatedR/lib/libopenblasp-r0.3.17.so
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] microbiome_1.14.0 vegan_2.5-7       lattice_0.20-45   permute_0.9-5     phyloseq_1.36.0   forcats_0.5.1    
>  [7] stringr_1.4.0     dplyr_1.0.7       purrr_0.3.4       readr_2.0.1       tidyr_1.1.3       tibble_3.1.4     
> [13] ggplot2_3.3.5     tidyverse_1.3.1  
> 
> loaded via a namespace (and not attached):
>   [1] Rtsne_0.15                  colorspace_2.0-2            hwriter_1.3.2              
>   [4] ellipsis_0.3.2              XVector_0.32.0              GenomicRanges_1.44.0       
>   [7] fs_1.5.0                    rstudioapi_0.13             fansi_0.4.2                
>  [10] lubridate_1.7.10            xml2_1.3.2                  codetools_0.2-18           
>  [13] splines_4.1.0               dada2_1.20.0                ade4_1.7-17                
>  [16] jsonlite_1.7.2              Rsamtools_2.8.0             broom_0.7.9                
>  [19] cluster_2.1.2               dbplyr_2.1.1                png_0.1-7                  
>  [22] shiny_1.6.0                 compiler_4.1.0              httr_1.4.2                 
>  [25] backports_1.2.1             assertthat_0.2.1            Matrix_1.3-4               
>  [28] fastmap_1.1.0               cli_3.0.1                   later_1.2.0                
>  [31] htmltools_0.5.2             tools_4.1.0                 igraph_1.2.6               
>  [34] gtable_0.3.0                glue_1.4.2                  GenomeInfoDbData_1.2.6     
>  [37] reshape2_1.4.4              ShortRead_1.50.0            Rcpp_1.0.7                 
>  [40] Biobase_2.52.0              cellranger_1.1.0            vctrs_0.3.8                
>  [43] Biostrings_2.60.0           rhdf5filters_1.4.0          multtest_2.48.0            
>  [46] ape_5.5                     nlme_3.1-153                iterators_1.0.13           
>  [49] rvest_1.0.1                 mime_0.11                   lifecycle_1.0.1            
>  [52] zlibbioc_1.38.0             MASS_7.3-54                 scales_1.1.1               
>  [55] promises_1.2.0.1            hms_1.1.0                   MatrixGenerics_1.4.0       
>  [58] parallel_4.1.0              SummarizedExperiment_1.22.0 biomformat_1.20.0          
>  [61] rhdf5_2.36.0                RColorBrewer_1.1-2          yaml_2.2.1                 
>  [64] latticeExtra_0.6-29         stringi_1.7.4               S4Vectors_0.30.0           
>  [67] foreach_1.5.1               BiocGenerics_0.38.0         BiocParallel_1.26.0        
>  [70] GenomeInfoDb_1.28.0         rlang_0.4.11                pkgconfig_2.0.3            
>  [73] bitops_1.0-7                matrixStats_0.61.0          Rhdf5lib_1.14.0            
>  [76] GenomicAlignments_1.28.0    tidyselect_1.1.1            plyr_1.8.6                 
>  [79] magrittr_2.0.1              R6_2.5.1                    IRanges_2.26.0             
>  [82] generics_0.1.0              DelayedArray_0.18.0         DBI_1.1.1                  
>  [85] pillar_1.6.2                haven_2.4.3                 withr_2.4.2                
>  [88] mgcv_1.8-37                 survival_3.2-13             RCurl_1.98-1.5             
>  [91] modelr_0.1.8                crayon_1.4.1                utf8_1.2.2                 
>  [94] tzdb_0.1.2                  jpeg_0.1-8.1                grid_4.1.0                 
>  [97] readxl_1.3.1                data.table_1.14.0           reprex_2.0.1               
> [100] digest_0.6.28               xtable_1.8-4                httpuv_1.6.3               
> [103] RcppParallel_5.1.4          stats4_4.1.0                munsell_0.5.0 


Could you please advise on whether or not I should get rid of NAs in my taxas (as they appear in the plot)? 
Cheers

**Comment by antagomir** [comment]
It is a user choice if you like to keep the NAs or remove, we do not have a specific recommendation on this. 

It would be advisable to switch to using the `aggregate_rare` function instead of `aggregate_top_taxa` because the latter will be removed in future versions of this package.

**Comment by marwa38** [comment]
Could you please show me with example how to use aggregate_rare for selecting top 10 taxa only 

> The code I used for the aggregate_top_taxa is as following:


```
ps_family_top10 <- microbiome::aggregate_top_taxa(ps.ra, "Family", top = 10) %>%
psmelt()
```
ps.ra is the phyloseq object of relative abundance

**Comment by marwa38** [comment]
Thanks very much Leo @antagomir 
I used the following method:
![image](https://user-images.githubusercontent.com/68851733/140815226-2d618335-e2fb-4bbc-abdf-2c0685561881.png)

Could you please advice as I am trying to use the code your kindly shared; why I am getting this error?
![image](https://user-images.githubusercontent.com/68851733/140815021-7dbb9b38-b241-4edf-ac43-c506dd67bc38.png)

**Comment by antagomir** [comment]
I think you are missing some parentheses in the command. Try:

`ntaxa(aggregate_rare(transform(dietswap, "compositional"), level="Genus", detection=1/100, prevalence=50/100))`
