### ISSUE TITLE
alpha diversity comparison between rarified and unrarified?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#168]
Hello 

I am trying to to make a comparison (at level of alpha diversities) between the rarified (ps.rare) versus the unrarified (ps.prev) phyloseq object as follows:

> ps.prev
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 180 taxa and 166 samples ]
sample_data() Sample Data:       [ 166 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 180 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 180 tips and 179 internal nodes ]
refseq()      DNAStringSet:      [ 180 reference sequences ] <

> ps.rare
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 119 taxa and 166 samples ]
sample_data() Sample Data:       [ 166 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 119 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 119 tips and 118 internal nodes ]
refseq()      DNAStringSet:      [ 119 reference sequences ] <

###to see which one I will go for as downstream analysis. The rarified worked fine for me as following but the unrarefied (ps.prev) gave me the following error:

`alpha.microbiome.unrare <- alpha(ps.prev, index = "all")
`
>Observed richness
Other forms of richness
Diversity
Evenness
Dominance
Rarity
Warning message:
In diversities_help(x, index = idx, zeroes = TRUE) :
  Some Fisher diversities could not be 
            estimated due to limited observations
`alpha.microbiome.unrare <- alpha(ps.prev, index = "all")
`
>Observed richness
Other forms of richness
Diversity
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
In addition: Warning message:
In log(1 + N/x) : NaNs produced

Can't find any help in the previous issues, could you please help me with this?
Cheers

**Comment by antagomir** [comment]
Can you provide version info for the microbiome package and then a reproducible example with a demonstration data set?

**Comment by antagomir** [comment]
I am closing this in absence of follow-up info. We can reopen if there is more information.

**Comment by marwa38** [comment]
Many Thanks 
The issue was solved I guess but I can't remember what was the source of the error.
