### ISSUE TITLE
error when using categorical data for associate function

### ISSUE THREAD

**Issue by tboonf** [microbiome/microbiome#169]
Hello,
I have been trying to use the associate function for correlation analysis. Analysis went smoothly when continuous data was used in spearman and pearson association analysis. However, when using categorical data, I have been getting the following error messages:
"Error in apply(qv, 1, function(x) { : dim(X) must have a positive length
In addition: Warning message:
In associate(x, y, method = "categorical", mode = "matrix", p.adj.threshold = 0.05,  :
  Considering only categorical annotations for factors"

This issue is reproducible and im at a lost on how this can be solved. 

Thank you so much for the help!

**Comment by antagomir** [comment]
Hmm can you provide a reproducible code example that generates this?

**Comment by tboonf** [comment]
Thanks for the quick response, Leo.
I first import a phyloseq object and convert it to the abundance count (x) and metadata (y) like you have in one of your tutorial:
https://microbiome.github.io/tutorials/Heatmap.html (peerj32). 

I then use the following code to run the association analysis for the categorical data:
correlations <- associate(x, y, method = "categorical", mode = "matrix", p.adj.threshold = 0.05, n.signif = 1) and received the said error message.

When doing exactly the same thing for continuos data and using the pearson/spearman correlation, the analysis completed without error. The original data set is huge, so i am attaching a smaller file here that will reproduce the same error message when doing the correlation analysis using categorical variables. 

> x
    OTU_3 OTU_14 OTU_1 OTU_6 OTU_20 OTU_4 OTU_9 OTU_2 OTU_12 OTU_21 OTU_23 OTU_19 OTU_13 OTU_17 OTU_16 OTU_7 OTU_15 OTU_11 OTU_10 OTU_18 OTU_22 OTU_5
C2    377     19   202    20     13    46    22    44      2      9      5      5      6      4      0     0      0      0      0      0      0     0
C1    342      0     0     0      0   103     0     0      0      0      0      0     10      0     44    70     43     20     46      9     19    33
C4B     0      0   773     0      0     0     0     1      0      0      0      0      0      0      0     0      0      0      0      0      0     0
C4S     0      0   774     0      0     0     0     0      0      0      0      0      0      0      0     0      0      0      0      0      0     0
C3      0      0     0     0      0     0     0   774      0      0      0      0      0      0      0     0      0      0      0      0      0     0
C5      0      0   774     0      0     0     0     0      0      0      0      0      0      0      0     0      0      0      0      0      0     0
    OTU_8
C2      0
C1     35
C4B     0
C4S     0
C3      0
C5      0


> y
         A     B
C2   Apple Green
C1   Apple Green
C4B Orange  Blue
C4S Orange  Blue
C3   Apple  Blue
C5  Orange  Blue

**Comment by antagomir** [comment]
can you provide an exact code example that generates this problem and that we can run as such?

**Comment by antagomir** [comment]
Thanks. 

It turned out that the categorical method is too problematic to include routinely in the `associate` function. This will require more consideration. I have therefore removed it from the associate function now, in the new commit.

This functionality is available through the `gktau` function for associating two univariate vectors/factors. The user can use this to build broader association tables, if necessary but also needs to think through it more carefully which I think is good default in this case.
