### ISSUE TITLE
top_taxa function for top 20 Genus?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#174]
Hello 

Could you please let me know how to use the top_taxa function to select the top 20 taxa at the Genus level from a phyloseq object?
I tried this one but it gave me an error:
`top_taxa(tax_table(ps.prev)["Genus"], n = 20)`
attached ps.prev for reproducibility. 

Many thanks 
Marwa
[ps.prev.zip](https://github.com/microbiome/microbiome/files/7574638/ps.prev.zip)

**Comment by antagomir** [comment]
Have you tested the example from `help(top_taxa)` and tried to modify this?

```
data(dietswap) #  example data in phyloseq format
topx <- top_taxa(dietswap, n=10)
```

**Comment by antagomir** [comment]
In order to use Genus level, you can then do

```
data(dietswap) #  example data in phyloseq format
pseq <- dietswap
pseq <- aggregate_taxa(pseq, level="Genus")
top_taxa(pseq, n=10)
```

**Comment by marwa38** [comment]
Thanks very much, Leo @antagomir 

Could you please advise how then I could transform that to relative abundance and melt for visualising as the way I am trying to do is working 

ps.prev.genus <- aggregate_taxa(ps.prev, level = "Genus")
`ps.prev.genus.top20 <- top_taxa(ps.prev.genus, n = 20)`

# Transform to relative abundance 
`ps.prev.genus.top20 <- transform_sample_counts(ps.prev.genus.top20, function(ASV) ASV/sum(ASV))`

# Melting for visualising
`ps.prev.genus_top20_melt <- ps.prev.genus.top20 %>% psmelt()`

**Comment by antagomir** [comment]
```
data(dietswap) #  example data in phyloseq format
pseq <- dietswap %>% aggregate_taxa(level="Genus")
pseq <- transform(pseq, "compositional")
df <-  psmelt(pseq)
```

p.s. could I ask to include the code comments also within the highlighted code <> ? Otherwise they are interpreted as markdown titles and rendered too large in the view.

**Comment by marwa38** [comment]
Thanks very much Leo @antagomir 

As a way to double-check.

I did the following:
```
ps.prev2.genus <- aggregate_taxa(ps.prev2, level = "Genus")
# select top 20 genus 
ps.prev2.genus.top20 <- top_taxa(ps.prev2.genus, n = 20)
# [1] "Pseudomonas"          "Aeromonas"            "Lactobacillus"        "Staphylococcus"      
# [5] "Streptococcus"        "Escherichia-Shigella" "Porphyromonas"        "Acinetobacter"       
# [9] "Arcicella"            "Pseudorhodobacter"    "Enterococcus"         "Luteolibacter"       
# [13] "Chryseobacterium"     "Polaromonas"          "Sphaerotilus"         "Rhodobacter"         
# [17] "Pedobacter"           "Arsenicibacter"       "Leuconostoc"          "Rhodoferax" 

# prune to have only which is genus top20 as phyloseq object 
ps.prev2.top20genus <- prune_taxa(ps.prev2.genus.top20, ps.prev2.genus)

# two steps for visualising purposes 
# transfrom 
ps.prev2.top20genus.transformed <- transform_sample_counts(ps.prev2.top20genus, function(ASV) ASV/sum(ASV))
# melt the phyloseq object 
ps.prev2.top20genus.transformed_melt <- ps.prev2.top20genus.transformed %>%
  psmelt()
```

Does this sound ok to you?
To use both microbiome and phyloseq packages in combination
Or you think something is not right

**Comment by antagomir** [comment]
seems fine
