### ISSUE TITLE
prevalence function

### ISSUE THREAD

**Issue by 1Hossainz** [microbiome/microbiome#176]
I was trying to use 'prevalence' function for core microbiome analysis. I followed the tutorial code and first time I got it right. Initial code is:
> ps.rel <- microbiome::transform(ps, "compositional")
> head(prevalence(ps.rel, detection = 1/100, sort = TRUE))

ps is the phyloseq object that I developed from dada2 output. After first time, always I am getting following error message (both R and RStudio in Windows). 

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'head': could not find function "prevalence"
Any clue what is happening! I appreciate your help.
Thanks.

**Comment by antagomir** [comment]
Hi! Have you tried to run this before the prevalence call:

`library(microbiome)`

**Comment by 1Hossainz** [comment]
Thank you Leo for quick response. I did run library(Microbiome) before running prevalence function. However, I have to install the package every new session of R as I don’t get it from library(Microbiome).

Regards,
Zakir

**Comment by antagomir** [comment]
What do you mean that you do not get it from `library(microbiome)` (note the lowercase! it is not "Microbiome" but "microbiome")? If the package has been installed, then this command is loading the library. Installation needs to be once, loading needs to be done per session. It works now?

**Comment by 1Hossainz** [comment]
Thanks! It is working now (m/M gave me so much pain).
