### ISSUE TITLE
top species in stacked bar chart?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#177]
Hello

Can you please let me know why I am seeing some columns in the stacked bar chart that don't have any of the species in them?
Just because the top 10 species are not present in those samples?

![image](https://user-images.githubusercontent.com/68851733/147502122-f2ca2866-00ea-462c-a603-c00c5f89d720.png)

Thanks very much.

**Comment by antagomir** [comment]
Yep, I think those species missing from those samples can explain this. What would be the alternative, expected behavior for the function?

**Comment by marwa38** [comment]
Thanks very much, Leo @antagomir 
What I did is I just removed those samples before running the visualisation code. 
But less number of samples in one rather than the other (marine vs vegetable).
