### ISSUE TITLE
Conversions data formats from phyloseq to TSE

### ISSUE THREAD

**Issue by taekwonleo-yuhao** [microbiome/microbiome#178]
Dear developers,
I am learning how to use mia to analyze microbiome data. But mia needs to convert the phyloseq format into TreeSummarizedExperiment format.
I try to use the function `makeTreeSummarizedExperimentFromPhyloseq` from mia. But it gives me an error message.
`library("mia"); packageVersion("mia")`
#[1] ‘1.3.9’

`ps1_ABX`
#phyloseq-class experiment-level object
#otu_table()   OTU Table:         [ 788 taxa and 1077 samples ]
#sample_data() Sample Data:       [ 1077 samples by 13 sample variables ]
#tax_table()   Taxonomy Table:    [ 788 taxa by 7 taxonomic ranks ]
#phy_tree()    Phylogenetic Tree: [ 788 tips and 786 internal nodes ]
# convert phyloseq to TSE

`GlobalPatterns_ABX_TSE <- makeTreeSummarizedExperimentFromPhyloseq(ps1_ABX) `

Error in validObject(.Object) :
  invalid class “SummarizedExperiment” object:
    ‘x@assays’ is not parallel to ‘x’
10. stop(msg, “: “, errors, domain = NA)
9. validObject(.Object)
8. initialize(value, ...)
7.i nitialize(value, ...)
6. new(“SummarizedExperiment”, NAMES = names, elementMetadata = rowData, 
colData = colData, assays = assays, metadata = as.list(metadata))
5. new_SummarizedExperiment(assays, ans_rownames, rowData, colData, 
metadata)
4. SummarizedExperiment(...)
3. SingleCellExperiment(...)
2. TreeSummarizedExperiment(assays = assays, rowData = rowData, 
colData = colData, rowTree = rowTree, referenceSeq = referenceSeq)
1. makeTreeSummarizedExperimentFromPhyloseq(ps1_ABX)

I tried to convert with another phyloseq file on my hand and get the same error. But I  successfully converted the phyloseq object from mia tutorials. Could you please tell me how to fix this issue?

Thanks,
Yuhao

**Comment by antagomir** [comment]
This issue is now in a wrong package repository (microbiome), it should be in the [issues of mia package](https://github.com/microbiome/mia/issues). Can you close this issue and move it there, and send the phyloseq object as RData file, we can have a look.

**Comment by taekwonleo-yuhao** [comment]
Sorry for my mistakes. I will close this issue and move it to the mia page.
