### ISSUE TITLE
ALR transform

### ISSUE THREAD

**Issue by tapj** [microbiome/microbiome#180]
Hi,

Would it be possible to add ALR transformation in `transform` function?

thank you

**Comment by antagomir** [comment]
Added, from the *compositions* package

Can you try

```
devtools::install_github("microbiome/microbiome")
library(microbiome)
data(dietswap)
#' # ALR transform
#' # The pseudocount must be specified explicitly
dietswap.transformed <- microbiome::transform(dietswap, 'alr', shift=1)
```

We have mainly stopped the development of the microbiome R package, although still providing some support & maintenance. We have moved to support the ecosystem around `TreeSummarizedExperiment`, another data container. We call this ecosystem _miaverse_ and the development work is active. More info at: microbiome.github.io/ - the ALR transformation is not available there at the moment but if this seems useful we should probably add. But if this is a single isolated case then I am not sure.
