### ISSUE TITLE
add_refseq

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiome#181]
This function is a utility which converts ASV sequences provided as taxa_names in phyloseq into ASVs ids and stores sequences in the refseq slot of phyloseq. however, if this is added then `Biostrings::DNAStringSet` has to be added to the imports. Is it ok to add this?
https://microsud.github.io/microbiomeutilities/reference/add_refseq.html
https://github.com/microsud/microbiomeutilities/blob/725776e6c8af3c15fbb394935bdb2cef885a445f/R/extensions.R#L100

**Comment by antagomir** [comment]
ok
