### ISSUE TITLE
issue with microbiome::add_besthit and microbiome::add_refseq

### ISSUE THREAD

**Issue by RunrunWu** [microbiome/microbiome#185]
Hi All,

I am new to Microbiome, and is just following the tutorial on my own.  I noticed that microbiome::add_besthit and microbiome::add_refseq doesn't seem to work at this point. R will return "Error: 'add_besthit' is not an exported object from 'namespace:microbiome", for example. I figured that microbiomeutilities::add_refseq solved the issue for microbiome::add_refseq, but am still not able to fix the issue for microbiome::add_besthit. Is there a quick fix for this issue? Thanks!

Best,
Runrun

**Comment by microsud** [comment]
Can you check if you have the latest version i.e. 1.17.41 of microbiome pkg installed from github? If not then you can install the development version from github using the steps below.

```
library(devtools) # Load the devtools package
install_github("microbiome/microbiome")
```
Before installing from github make sure you restart R/Rstudio.

Hope this helps.

Best regards,
Sudarshan
