### ISSUE TITLE
relative abundance of each taxa?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#186]
hello ... I was wondering if there is a function you provide to calculate the percent of each of the relative abundance taxa from the total abundance?
as you can kindly see I created that the ones below 1% in abundance but I need to create or produce a table which contains how each taxa constitutes of the total abundance
![image](https://user-images.githubusercontent.com/68851733/160648541-c0aaa171-711e-4715-b3ef-a3cad8a54005.png)
Thanks in advance 

P.S. I found something like this in qiime2 but I already ran my analysis outside using microbiome package, etc in Rstudio 
https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2019.4%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftaxa-bar-plots.qzv

**Comment by antagomir** [comment]
Did you check function `microbiome::transform` that should do it
