### ISSUE TITLE
Error in access(object, "sam_data", errorIfNULL) :   sam_data slot is empty.

### ISSUE THREAD

**Issue by confetti91** [microbiome/microbiome#188]
Hello all!

So, I'm kinda new on microbiome things and I'm trying to opem my data in R to work on this. So, my problem is with the sample_data in my .biom file. I opem my file using `import_biom("otu_table_mc2_w_tax.biom", "rep_set.tre", "new_refseqs.fna", parseFunction=parse_taxonomy_greengenes)` where the .biom is my file as well, the .tre is my phylogeny and the .fna file is my refseq. But whem I go ahead in the code, I'm get stucked with this error message `Error in access(object, "sam_data", errorIfNULL) : 
  sam_data slot is empty.` 

So, what can I do to fix this problem? there is a way to put this sample_data inside this .biom file, and more important, what is this sample_data? (sorry about this silly question)

Thank you.

**Comment by confetti91** [comment]
If this can help, I received all of those files from qiime2

![image](https://user-images.githubusercontent.com/39387139/161317206-ebd6b6ff-28bd-4a49-819a-02f901656c4e.png)

and when I open my .biom on R i got this:

`pseq<-import_biom("otu_table_mc2_w_tax.biom", "rep_set.tre", "new_refseqs.fna", parseFunction=parse_taxonomy_greengenes)
pseq`

`phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4147 taxa and 30 samples ]
tax_table()   Taxonomy Table:    [ 4147 taxa by 14 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 4147 tips and 4141 internal nodes ]
refseq()      DNAStringSet:      [ 4147 reference sequences ]`

**Comment by antagomir** [comment]
The function `import_biom` is from the _phyloseq_ R/Bioc package, not from the _microbiome_ R/Bioc package. For questions related to _phyloseq_ package, check the phyloseq documentation and/or [github site](https://github.com/joey711/phyloseq/).
