### ISSUE TITLE
relative abundance pvalues?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#189]
Hello guys

Could you please let me know if there is an option using the `microbiome `package to draw the relative abundance pvalues beside the figure?
(like the attached figure)
Thanks 
M
![image](https://user-images.githubusercontent.com/68851733/163782359-dd3fbafb-d197-4ca6-ae4b-2d8402fd9436.png)

**Comment by antagomir** [comment]
No there isn't direct option for that, one would need to manipulate the resulting ggplot objects manually.

PRs also welcome, as always.

**Comment by marwa38** [comment]
Thanks for your reply. 
Apart from the figure do you run differential abundance analysis? most probably is it better to be run on rarefied or unrarefied data?

**Comment by antagomir** [comment]
Quite often research project run DA analysis, there is vast literature discussing the pros & cons of rarification and this project does not provide specific recommendations.
