### ISSUE TITLE
boxplot_alpha

### ISSUE THREAD

**Issue by benedil** [microbiome/microbiome#190]
Hello, 
I'm running through the alpha diversity tutorial and have hit a strange wall.  The boxplot_alpha function seems to be completely missing from the package?  I just checked for updates, made sure the package was loaded, restarted R... it doesn't show up in the help index and when I try to just run the command I get:
`Error in boxplot_alpha(combined_taxa_physeq, index = "chao1", x_var = "location",  : 
  could not find function "boxplot_alpha"`

Am I missing something really obvious?

Thanks!
LS

**Comment by microsud** [comment]
Hi! Did you update the pkg from GitHub? What is the version of pkg installed in your system?

**Comment by benedil** [comment]
Aha!  Thank you, I had only been checking for updates inside RStudio, so nothing was showing up.  I reinstalled from git to get the latest version.
