### ISSUE TITLE
tutorial core micrbiota query?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#191]
Hello 

A quick query regarding tutorial: https://microbiome.github.io/tutorials/Core.html
I can't understand fully how we can select core microbiota at 50% prevalence? what does this mean?
Does this mean that core microbes are only present in 50% of the samples? so then they are considered core?
`core.taxa.standard <- core_members(pseq.rel, detection = 0, prevalence = 50/100)`
Could you please clarify?

Many thanks 
M

**Comment by antagomir** [comment]
This selects taxa that are present in >50% of the samples at a nonzero (detection>0) abundance.

**Comment by marwa38** [comment]
From your experience and literature, 80% of samples would be enough to be considered core?

**Comment by antagomir** [comment]
Yes you can choose whatever number you prefer. Perhaps the function should have a better name but the thresholds are chosen by the user. We have now moved further development to a new package [mia](https://github.com/microbiome/mia) which is a bit different. There the function is `getPrevalentTaxa`

**Comment by marwa38** [comment]
Thanks Leo :)
