### ISSUE TITLE
Error in "Divergence within individual over Time" parameters

### ISSUE THREAD

**Issue by cdeschamps63** [microbiome/microbiome#194]
Hello, 
I'd like to test the divergence within individual over time in my metabarcoding data from a phyloseq object. I used the tuto found here : https://microbiome.github.io/tutorials/Betadiversity.html

I would like to examined the stability of microbial cultures based on Bray-Curtis similarity by computing the Bray-Curtis similarity of each daily sample with the average of all other daily samples to gauge the long-term community stabilization. To do so I would like to test a 3-point moving window average but I failed. 

This is the representation I would like to obtain (figure extracted from Jin et al. 2022): 
<img width="794" alt="Capture d’écran 2022-07-22 à 15 21 08" src="https://user-images.githubusercontent.com/101580346/180471271-9e3132db-d75a-4141-bcf1-875d0dce69ff.png">

This is my code : 
`
pseq <- physeq
s <- "dog-2" 
b <- "luminal medium"

pseq <- subset_samples(physeq, subject == s & sample.type == b) 

sample_data(pseq)$sample <- sample_data(pseq)$sample.id

df <- meta(pseq) %>% arrange(days)

beta <- c() 
s0 <- subset(df, days == 1)$sample

a <-microbiome::abundances(microbiome::transform(pseq, "compositional")) 
for (tp in df$days[-3]) {
  st <- sample(subset(df, days == tp)$sample, 1)
  stm3 <- sample(subset(df, days == tp-3)$sample, 1)
  b <- vegdist(rbind(a[, stm3], a[, st]), method = "bray")
  beta <- rbind(beta, c(tp, b))
  }`

I have received the following error : Erreur dans tp - 3 : argument non numérique pour un opérateur binaire.

I also tried :  stm3 <- sample(subset(df, days == df$days[tp-3])$sample, 1) but it failed

Can you please help me with this issue ? 
Thank you in advance,
Charlotte

**Comment by antagomir** [comment]
Thanks for the question.

We have moved most new developments into a new framework based on the TreeSummarizedExperiment data container, a beta version of tutorial is here, [OMA](microbiome.github.io/OMA/).

We might be able to provide an example but this seems to involve some new coding. Would you mind if we provide the example in that new system instead (and not based on phyloseq)?

**Comment by antagomir** [comment]
Ok - I have now added some examples in [miaTime](https://microbiome.github.io/miaTime/articles/).

These are based on the mia framework and TreeSummarizedExperiment.

In particular the minimalgut examples. The website is currently building, should be live with the updates tomorrow at the latest.

**Comment by antagomir** [comment]
Some examples are now [here](https://microbiome.github.io/miaTime/articles/minimalgut.html).

**Comment by cdeschamps63** [comment]
This must be very interesting for me and seems to be very adapted to my work. 
I will have a look on it today and let you know, 

Thank you very much for your reactivity !

**Comment by antagomir** [comment]
I forgot to mention you should install the latest development versions of the packages

devtools::install_github("microbiome/mia")
devtools::install_github("microbiome/miaTime")
