### ISSUE TITLE
Colors in plot

### ISSUE THREAD

**Issue by lynneitelson** [microbiome/microbiome#195]
Hi! 

I used the microbiome package in order to create a relative abundance graph. I cant get each Phylum to have its own color. What might me the problem? 

Thnkyou! 

![image](https://user-images.githubusercontent.com/109670658/189101421-c1eabedd-c188-486c-8c1d-3af9d00b4ef5.png)

``
total_samples <- phyloseq::nsamples(ps)
ps.pruned <- prune_taxa(taxa_sums(ps) >0, ps)

# merge all taxa that are detected rare
pseq.phylum <- aggregate_rare(ps, level="Phylum", detection = 1/100, prevalence = 50/100)

# Remove the "p__" before the family names
taxa_names(pseq.phylum) <- gsub("p__", "", taxa_names(pseq.phylum) )

p.phylum <- plot_composition(pseq.phylum,
                             sample.sort = NULL,
                             otu.sort = NULL,
                             x.label = "empo_3",
                             plot.type = "barplot",
                             verbose = FALSE) +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank()) +
  xlab("Bacteria composition")
 

p.phylum
``

**Comment by antagomir** [comment]
Hmm you have aggregated the data at Phylum level and each phylum has its own color. I am not sure if I understood the question.

**Comment by lynneitelson** [comment]
For example, its difficult to tell the difference between chloroflexi and cyanobacteria. In the tutorial the colors of the different phyla are more diverse, thus the differences in occurrence is noticeable. 

Thanks a lot!

Lynne

**Comment by antagomir** [comment]
If you have too many phyla then it is difficult to choose distinguishable colors. Consider showing just the most prevalent ones for instance.
