### ISSUE TITLE
Problem with otu_table

### ISSUE THREAD

**Issue by LilEigenValue** [microbiome/microbiome#196]
Running this code below, but the OTU and phyloseq objects of going through with 0B of data

OTU = otu_table(a.otu, taxa_are_rows = TRUE)
physeq<-phyloseq(OTU)
pseq.rel<- microbiome::transform(physeq, "compositional")
core.taxa.standard <- core_members(pseq.rel, detection = 0, prevalence = 50/100)
core.taxa.standard
<img width="758" alt="Screen Shot 2022-09-14 at 11 30 57 PM" src="https://user-images.githubusercontent.com/65837480/190307494-2f343394-ba43-48f1-bd90-f7b1ed3dd51d.png">

**Comment by antagomir** [comment]
Is it the `otu_table` function that is the problem here?

**Comment by LilEigenValue** [comment]
The function worked a few weeks ago but hen I updated and it won't pull in any data

**Comment by antagomir** [comment]
I mean, it would be important to know on which exact line this code breaks. The problem may be before the last line. We need output per line, or a phyloseq object.

**Comment by antagomir** [comment]
I am closing this in absence of follow-up info. We can reopen if there is more information.
