### ISSUE TITLE
error with the plot

### ISSUE THREAD

**Issue by lynneitelson** [microbiome/microbiome#199]
Hi, 
 I ran the following code and at the end got the next error: 

![image](https://user-images.githubusercontent.com/109670658/197380338-7903a54e-c3a7-4345-a4f1-305c4bb67824.png)

what might be the problem? 

Thank you!

Lynne

`library(microbiome)
#plot_count_abundance
library(phyloseq)
library(ggplot2)

#check how many samples are there

total_samples <- phyloseq::nsamples(ps)
ps.pruned <- prune_taxa(taxa_sums(ps) >0, ps)

# merge all taxa that are detected rare
pseq.phylum <- aggregate_rare(ps, level="Phylum", detection = 1/100, prevalence = 50/100)

# Remove the "p__" before the family names
taxa_names(pseq.phylum) <- gsub("p__", "", taxa_names(pseq.phylum) )

p.phylum <- plot_composition(ps.pruned,
                             sample.sort = NULL,
                             otu.sort = NULL,
                             x.label = "empo_3",
                             plot.type = "barplot",
                             verbose = FALSE) +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank()) +
  xlab("Bacteria composition")
 

p.phylum
`

**Comment by antagomir** [comment]
I expect it is a generic problem with ggplot2 unrelated to microbiome R package?

**Comment by lynneitelson** [comment]
its possible, i will post on the ggplot2 package page

thank you!
