### ISSUE TITLE
does microbiome::transform compositional log-transform my data also?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#201]
Hi guys 
I have been recently informed that I can't run differential abundance statistical tests as the Kruskal test on data without log-transforming it first. 
I already ran my analysis using `microbiome::transform(ps.prev.phy2, "compositional")` 
My query is does this (log) transform my data?
thank you 
M

**Comment by antagomir** [comment]
The compositional transformation just calculates percentages, like for each sample x/sum(x) across taxa -> after this each sample sums up to 100% (ie number 1).

CLR transformation does log as well but also other things, see some sources.

However Kruskal test is invariant to log, it shouldn't matter at all if you use log or not:

```
library(microbiome)
data(dietswap)
x <- abundances(dietswap)
m <- meta(dietswap)
>kruskal.test(1 + x["Dialister",] ~ m$sex)$p.value
[1] 0.001885639
> kruskal.test(log10(1 + x["Dialister",]) ~ m$sex)$p.value
[1] 0.001885639

```

**Comment by marwa38** [comment]
Thanks so much for your answer 
Could you please let me know what is 

> CLR transformation

?

**Comment by marwa38** [comment]
@antagomir So why do you think it is advisable to clr-transform of compositional data before statistical analysis although Kruskal or Wilcoxon rank sum tests are invariant to logarithmic or monotonic transformations?

**Comment by antagomir** [comment]
I am afraid we cannot give general statistical advice on this forum. There are pros & cons that depend also on the situation. If you do not clr transform then you ignore compositionality bias in your comparisons. If do, then you distort the data with pseudocount. In some cases this is a larger issue than in others.
