### ISSUE TITLE
relative or absolute abundances for statistical analysis (Differential abundance analysis), any thoughts?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#202]
Hi @antagomir 
In response to runing kruskal test for differential abundance analysis,
Could you please let me know if it is best to run the non-parametric test (kruskal test, for example) on relative abundances or absolute abundances of the microbota? 

        The compositional transformation just calculates percentages, like for each sample x/sum(x) across taxa -> after this each sample sums up to 100% (ie number 1).

CLR transformation does log as well but also other things, see some sources.

However Kruskal test is invariant to log, it shouldn't matter at all if you use log or not:

```
library(microbiome)
data(dietswap)
x <- abundances(dietswap)
m <- meta(dietswap)
>kruskal.test(1 + x["Dialister",] ~ m$sex)$p.value
[1] 0.001885639
> kruskal.test(log10(1 + x["Dialister",]) ~ m$sex)$p.value
[1] 0.001885639

```

_Originally posted by @antagomir in https://github.com/microbiome/microbiome/issues/201#issuecomment-1304622130_
      

As an update I ran wilcox test on absolute abdunances (with and without log transformation) and found that there were no significant changes between different groups whereas when I ran wilcox test on relative abundances (with and without log transfromation), significant stat differences were found for both log transfromated and not log transformed.
Would you like to share your thoughts?

**Comment by antagomir** [comment]
Microbiome data sets are compositional. You should use compositionality aware transformations, such as clr, to remove bias in comparisons. See e.g. Gloor et al. (2017): https://www.frontiersin.org/articles/10.3389/fmicb.2017.02224/full

Of course such approaches may have other problems. This github site is not really intended for deep statistical advise on microbiome data analysis, this is mainly to fix technical issues with the package.
