### ISSUE TITLE
plot_regression() on phyoseq?

### ISSUE THREAD

**Issue by marwa38** [microbiome/microbiome#205]
Could I use plot_regression() to plot phyloseq object taxa on y-axis and one column from meta(phyloseq) on x-axis? https://microbiome.github.io/tutorials/Regression.html
Thanks in advance
M

**Comment by antagomir** [comment]
This function takes data.frame as input. You can do that if you add the signal from your taxa to the metadata and then use the plotting as shown in the examples.
