### ISSUE TITLE
Error when using boxplot_alpha

### ISSUE THREAD

**Issue by marinachen** [microbiome/microbiome#208]
Hi I'm trying to use the boxplot_alpha() function to plot alpha diversity across sample types, but I ran into an error that seems indicating that I do not have this function. Could you please help troubleshoot? Thank you!
```
> p.shannon <- boxplot_alpha(pseq, 
+                            index = "shannon",
+                            x_var = "sex",
+                            fill.colors = c(female="cyan4", male="deeppink4"))
Error in boxplot_alpha(pseq, index = "shannon", x_var = "sex", fill.colors = c(female = "cyan4",  : 
  could not find function "boxplot_alpha"
```

**Comment by antagomir** [comment]
Did you run library(microbiome) before applying this command?

Can you provide output of sessionInfo()

**Comment by marinachen** [comment]
Hi @antagomir thank you for getting back! Please see attached sessioninfo() output. I do have microbiome package installed. I was able to use other functions except barplot_alpha(). I also tried to pull out help page with `?boxplot_alpha()` and it returns `Error in .helpForCall(topicExpr, parent.frame()) : 
  no methods for ‘boxplot_alpha’ and no documentation for it as a function` Thank you for your help!

`R version 4.1.0 (2021-05-18)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbiome_1.16.0 ggpubr_0.4.0      ggplot2_3.4.2     phyloseq_1.38.0  

loaded via a namespace (and not attached):
  [1] nlme_3.1-152           bitops_1.0-7           matrixStats_0.60.0     doParallel_1.0.17      RColorBrewer_1.1-2     GenomeInfoDb_1.30.1   
  [7] tools_4.1.0            backports_1.2.1        utf8_1.2.2             R6_2.5.0               vegan_2.6-4            DBI_1.1.1             
 [13] BiocGenerics_0.40.0    mgcv_1.8-35            colorspace_2.0-2       permute_0.9-7          rhdf5filters_1.6.0     ade4_1.7-22           
 [19] GetoptLong_1.0.5       withr_2.5.0            tidyselect_1.2.0       curl_4.3.2             compiler_4.1.0         cli_3.6.1             
 [25] Biobase_2.54.0         labeling_0.4.2         scales_1.2.1           stringr_1.5.0          digest_0.6.27          foreign_0.8-81        
 [31] rio_0.5.27             XVector_0.34.0         pkgconfig_2.0.3        rlang_1.1.0            GlobalOptions_0.1.2    readxl_1.3.1          
 [37] rstudioapi_0.13        farver_2.1.0           shape_1.4.6            generics_0.1.0         jsonlite_1.7.2         dplyr_1.1.1           
 [43] zip_2.2.0              car_3.0-11             RCurl_1.98-1.12        magrittr_2.0.1         GenomeInfoDbData_1.2.7 biomformat_1.22.0     
 [49] Matrix_1.3-3           Rcpp_1.0.7             munsell_0.5.0          S4Vectors_0.32.4       Rhdf5lib_1.16.0        fansi_0.5.0           
 [55] abind_1.4-5            ape_5.7-1              lifecycle_1.0.3        stringi_1.7.3          carData_3.0-4          MASS_7.3-54           
 [61] zlibbioc_1.40.0        Rtsne_0.16             rhdf5_2.38.1           plyr_1.8.6             grid_4.1.0             parallel_4.1.0        
 [67] forcats_0.5.1          crayon_1.4.1           lattice_0.20-44        Biostrings_2.62.0      haven_2.4.2            splines_4.1.0         
 [73] multtest_2.50.0        circlize_0.4.15        hms_1.1.0              ComplexHeatmap_2.10.0  pillar_1.9.0           igraph_1.4.1          
 [79] rjson_0.2.21           ggsignif_0.6.2         reshape2_1.4.4         codetools_0.2-18       stats4_4.1.0           glue_1.6.2            
 [85] data.table_1.14.8      BiocManager_1.30.20    png_0.1-8              vctrs_0.6.1            foreach_1.5.2          cellranger_1.1.0      
 [91] gtable_0.3.0           purrr_1.0.1            tidyr_1.1.3            clue_0.3-64            openxlsx_4.2.4         broom_0.7.9           
 [97] rstatix_0.7.0          viridisLite_0.4.0      survival_3.2-11        tibble_3.2.1           iterators_1.0.14       IRanges_2.28.0        
[103] cluster_2.1.2          ellipsis_0.3.2        `

**Comment by antagomir** [comment]
We are now in microbiome version 1.21.1. Yours is 1.16.0.

Can you updgrade with
devtools::load_all("microbiome/microbiome")

then restart R and try again.

**Comment by marinachen** [comment]
Thank you for the advice. I just tried and unfortunately there was another error when running that upgrade code. 

`> devtools::load_all("microbiome/microbiome")
Error in `value[[3L]]()`:
! Could not find a root 'DESCRIPTION' file that starts with '^Package' in microbiome/microbiome.
ℹ Are you in your project directory and does your project have a 'DESCRIPTION' file?
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In normalizePath(path) :
  path[1]="microbiome/microbiome": No such file or directory`

**Comment by antagomir** [comment]
Ok thanks.
Can you then try:

BiocManager::install("microbiome")

**Comment by marinachen** [comment]
Thanks and apologies below will be a very long output.
```
> BiocManager::install("microbiome")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.14 (BiocManager 1.30.20), R 4.1.0 (2021-05-18)
Installation paths not writeable, unable to update packages
  path: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
  packages:
    backports, bit, blob, boot, broom, callr, car, carData, class, cli, clipr, cluster, codetools, colorspace, conquer, corrplot, cpp11,
    crayon, curl, data.table, DBI, dbplyr, digest, dplyr, dtplyr, evaluate, fansi, farver, forcats, foreign, fs, gargle, generics, ggplot2,
    ggpubr, ggrepel, ggsci, ggsignif, glue, googledrive, googlesheets4, gtable, haven, highr, hms, htmltools, httr, isoband, jsonlite, knitr,
    lattice, lifecycle, lme4, lubridate, magrittr, maptools, markdown, MASS, Matrix, MatrixModels, matrixStats, mgcv, mime, minqa, modelr,
    naniar, nlme, nloptr, nnet, norm, openssl, openxlsx, pbkrtest, pillar, plyr, polynom, processx, ps, purrr, quantreg, R6, RColorBrewer,
    Rcpp, RcppArmadillo, RcppEigen, readr, readxl, reprex, rio, rlang, rmarkdown, rpart, rstatix, rstudioapi, rvest, scales, sp, spatial,
    stringi, stringr, survival, sys, tibble, tidyr, tidyselect, tidyverse, tinytex, tzdb, utf8, uuid, vctrs, viridis, viridisLite, visdat,
    vroom, withr, xfun, xml2, yaml, zip
Old packages: 'igraph', 'zoo'
Update all/some/none? [a/s/n]: 
a
Warning: unable to access index for repository https://bioconductor.org/packages/3.14/bioc/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.14/bioc/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.14/data/annotation/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.14/data/annotation/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.14/data/experiment/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.14/data/experiment/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.14/workflows/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.14/workflows/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.14/books/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.14/books/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'

  There are binary versions available but the source versions are later:
       binary source needs_compilation
igraph  1.4.1  1.4.2              TRUE
zoo    1.8-11 1.8-12              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
```
After I replied Yes, it's another extremely long verbose and eventually looked like this:
```
make: /opt/R/arm64/bin/gfortran: No such file or directory
make: *** [vendor/arpack/dgetv0.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/Users/marina/Library/R/arm64/4.1/library/igraph’
* restoring previous ‘/Users/marina/Library/R/arm64/4.1/library/igraph’
* installing *source* package ‘zoo’ ...
** package ‘zoo’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c coredata.c -o coredata.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c init.c -o init.o
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include  -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c lag.c -o lag.o
clang -arch arm64 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o zoo.so coredata.o init.o lag.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Users/marina/Library/R/arm64/4.1/library/00LOCK-zoo/00new/zoo/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (zoo)

The downloaded source packages are in
	‘/private/var/folders/7f/ktdg7kpn35g8_3yjky_tlskc0000gr/T/Rtmp8qqDx4/downloaded_packages’
Warning messages:
1: package(s) not installed when version(s) same as or greater than current; use `force = TRUE` to re-install: 'microbiome' 
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘igraph’ had non-zero exit status
```

**Comment by antagomir** [comment]
It seems you need to install igraph package. This may require that you first install some other software but that depends on your OS. You can search for igraph installation issues and try to get that installed first, then try again.

**Comment by marinachen** [comment]
Hi, thank you! I figured it out that it was the M1 issue that prevent me from directly accessing packages via BiocManager. All solved now. Thank you!!
