### ISSUE TITLE
CLR Transformation

### ISSUE THREAD

**Issue by JLammons14** [microbiome/microbiome#212]
I had a quick question related to the CLR transformation using the the transform() function. I wanted to clarify if abundance data needs to be transformed to relative abundance prior to CLR transformation. Secondly, does transform() calculate CLR based on relative abundance or count data. 

Thanks

**Comment by antagomir** [comment]
The microbiome pacakge does transform data to compositional data before CLR.

That is not necessary, CLR can also be applied to count data. The new framework that is based on TreeSummarizedExperiment is allowing to do both. See the mia R/Bioc package for that.
