### ISSUE TITLE
read_phyloseq / read_biom2plyloseq does not read tab-delim meta-data files

### ISSUE THREAD

**Issue by biobee** [microbiome/microbiome#215]
Dear all,

The function read_phyloseq() cannot import a meta-data file in tab-delimited format, since read_biom2phyloseq as opposed to read_csv2phyloseq does not have a "sep" and therefore cannot import tab-delimited meta-data files.

line 36/37:
 map <- read.csv(metadata.file, 
                check.names = FALSE, row.names = 1)

Could "sep" be added to read_biom2phyloseq like in read_csv2phyloseq ?

Best regards

**Comment by antagomir** [comment]
Yes, possible. 

Any chance preparing a pull request on this..?

**Comment by antagomir** [comment]
closed via #216
