### ISSUE TITLE
plot_core on phyloseq obtained from the core function

### ISSUE THREAD

**Issue by chrissy005** [microbiome/microbiome#218]
Hello, 

Is it possible to  plot_core on a phyloseq object which is produced after using the core or aggregate_rare function?

When I try to use the phyloseq obtained from the core or aggregate_rare function, I get an error message:

"Warning: The plot_core function is typically used with compositional 
                data. The data is not compositional. Make sure that you
                intend to operate on non-compositional data."

The initial phyloseq with raw counts were transformed to compositional counts using the microbiome package.

**Comment by antagomir** [comment]
Thanks for the suggestion. We can improve this by accepting a pull request but the active development of this package is now halted as we have moved on to support the extended TreeSummarizedExperiment framework documented in microbiome.github.io/OMA - if necessary we can provide more detailed examples on how to do the required operations in that system.
