### ISSUE TITLE
microbiome::plot_composition, legend issue in composition plot

### ISSUE THREAD

**Issue by CecileBlanchon** [microbiome/microbiome#222]
Hello,

I am using R (version 4.2.3 (2023-03-15)) with phyloseq (1.42.0), qiime2 (0.99.6), microbiome (1.20.0). 
I am trying to plot community composition only with the 10 more abundant species with the microbiome::plot_composition command :
 > microbiome::plot_composition(physeq_object, taxonomic.level = "Species", average_by = "Experiment.ID", x.label = "Experiment.ID", numberOfTaxa=10)

I always have all the OTU not only the 10 more abundant and I receive the OTU ID as my legend rather than the bacterial name. Is there a way to plot community composition of a phyloseq object with the microbiome package with only the 10 more abundant species and species names as legend ?

Thanks,

**Comment by antagomir** [comment]
We maintain microbiome R package through these issues but generic consultation, we recommend to use [Gitter](https://app.gitter.im/#/room/#microbiome:gitter.im) or [Bioconductor support forum](https://support.bioconductor.org/).

On another note, while we continue to maintain the phyloseq-based microbiome pkg, active development and consultation has ceased. We have shifted to supporting the TreeSummarizedExperiment-based R/Bioconductor framework for microbiome data science, see the [miaViz::plotAbundance](https://microbiome.github.io/miaViz/reference/plotAbundance.html) function and [OMA Gitbook](https://microbiome.github.io/OMA) (chapter 8 on community composition) for more details.
