### ISSUE TITLE
Wrong naming in merge_taxa2

### ISSUE THREAD

**Issue by robbueck** [microbiome/microbiome#223]
I have the issue that when I merge a list of taxa with merge_taxa2, I get one taxon named according to the `name` variable with NA on all taxonomic levels and the last taxon in the table keeping it's name but having all taxonomic levels renamed according to `name`. I think the last part in the function:
```
  taxa_names(x2) <- gsub(mytaxa[[1]], name, taxa_names(x2))
  tax_table(x2)[nrow(tax_table(x2)), ] <- rep(name, ncol(tax_table(x2)))
```
should be 
```
  taxa_names(x2) <- gsub(mytaxa[[1]], name, taxa_names(x2))
  tax_table(x2)[1, ] <- rep(name, ncol(tax_table(x2)))
```

**Comment by antagomir** [comment]
Ah, right. Thanks for reporting.

PR to fix is welcome, or we may do later as the time will allow. 

This microbiome pkg is based on phyloseq. Minimum maintenance is provided but the package is not any more actively developed as we switched to the TreeSummarizedExperiment-based framework with mia and other pkgs.

**Comment by robbueck** [comment]
Did a PR

**Comment by antagomir** [comment]
Thanks, merged. We can add you as contributor (ctb) in DESCRIPTION if you wish.

**Comment by robbueck** [comment]
Nice, thanks!
