### ISSUE TITLE
Sample Names of the plot_composition() function show wrong samples!

### ISSUE THREAD

**Issue by wolass** [microbiome/microbiome#3]
When I plot with phyloseq i get this:

![rplot01](https://cloud.githubusercontent.com/assets/2356167/10861159/9a1b99f0-7f77-11e5-9e4b-0cb3faa59d6a.png)

PLEASE LOOK AT THE TWO HIGHEST ABUNDANCES and the CORRESPONDING SAMPLE NAMES

and when I plot with plot_composition() I get this:

![rplot02](https://cloud.githubusercontent.com/assets/2356167/10861174/f8fcadd8-7f77-11e5-8904-a938f2bc5f45.png)

Notice that the sample names are totally incorrect!

**Comment by antagomir** [comment]
Thanks a lot for pointing this out. I was too hasty (fixing this while on vacation..). It should be fixed now as far as I can see. Just let me know if there are any further issues.
