### ISSUE TITLE
format_phyloseq

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#31]
Two requests: 

1) This could utilize directly the more generic phyloseq functions parse_taxonomy_qiime / _default / _greengenes (check the help of those functions for examples) that know how to perform a similar parsing than is being done in the beginning of this script. Since phyloseq is a central dependency anyway it would make sense to utilize the readily available solution from there. This could simplify the code within format_phyloseq, help to standardize the procedures, and help to avoid bugs by not duplicating solutions.

2) Then it is unclear whether the format_phyloseq function is needed in the first place. Perhaps we could obtain the same by just writing 1-2 lines of code like 'tax_table(x) <- parse_taxonomy_qiime(tax_table(x))' and this could be shown in the tutorial examples. Better not write new functions that just duplicate what is available otherwise. But: I did not examine this properly, so if there is essential functionality on top of the phyloseq parsers then that can justify the format_phyloseq function. Even then, the phyloseq parsers should be used where possible to simplify the code and avoid duplication.

Could you have a look when the time allows ?

**Comment by microsud** [comment]
Apology for late reply. The Phyloseq works best with greengenes and the default function still needs to adding of rank names. The main reason to add this function is to add the OTU ids and the best taxonomic classification for unclassified OTUs. I can remove the parsing function and give a seperate one line code to solve this issue in the rmd file as suggested on the phyloseq github page?

**Comment by antagomir** [comment]
If the format_phyloseq function can be replaced with a simple 1-3 line example in Rmd tutorial by taking advantage of existing package then I would prefer that solution. Avoiding duplication is essential for successful tool building.

**Comment by antagomir** [comment]
In addition, it would be necessary to add a brief explanation on the purpose of these functions (format_phyloseq and plot_prevalent_taxa) in the tutorial (Composition.Rmd).

**Comment by microsud** [comment]
@antagomir I think you are right. It is better to remove the <format_phyloseq> . I have already included a part of it in the <read_phyloseq> function to change headers to taxonomic informations.  Rest changes of adding OTU IDs are more dependent on user requirements so we can provide support if there is someone asking for this utility.

**Comment by antagomir** [comment]
Ok, can you remove it (and vignette examples) for your next PR ?

**Comment by antagomir** [comment]
Also examples from manpages (roxygen) and vignette (gh-pages repo) have to be removed/replaced. 

Can you also close this issue once that is done.

**Comment by antagomir** [comment]
There is still one occurrence: 

lei@kone:~/Rpackages/microbiome/R$ grep format_phylo *
plot_taxa_prevalence.R:#'   p0.f <- format_phyloseq(p0)

**Comment by antagomir** [comment]
Did you test the updated example before push ?

> ### ** Examples
> 
>   data(DynamicsIBD)
>   # Pick data subset to speed up example
>   p0 <- subset_samples(DynamicsIBD, sex == 'male' & timepoint == 1)
>   p <- plot_taxa_prevalence(p0, 'Phylum')
Error in data.frame(abundance = log(tax.abun), prevalence = tax.prev,  : 
  arguments imply differing number of rows: 10996, 0
Calls: plot_taxa_prevalence -> data.frame
Execution halted

**Comment by microsud** [comment]
@antagomir My history had the variables saved. After clearing history, figured the bug and now fixed it.

**Comment by antagomir** [comment]
Have you pushed the changes? I do not see any changes.

**Comment by microsud** [comment]
@antagomir The changes are made in the devel branch.

**Comment by microsud** [comment]
@antagomir also format_phyloseq.rd is removed from devel branch.

**Comment by antagomir** [comment]
works now
