### ISSUE TITLE
evenness indices

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#34]
Following [this article](http://www.pnas.org/content/113/21/5970.full) add evenness metrics that perform well according to a series of [statistical requirements](http://www.jstor.org/stable/3545749), including lacking a strong bias toward very large or very small abundances, independence of richness (S), and scaling between zero (no evenness) and one (perfect evenness). These included Smith and Wilson’s indices (Evar and EQ), Simpson’s evenness (E1/D), Bulla’s index (O), and Camargo’s index (E′) [See Magurran AE, McGill BJ , eds (2011) Biological Diversity: Frontiers in Measurement and Assessment (Oxford Univ Press, Oxford), Vol 12 as well as http://www.jstor.org/stable/3545749].

**Comment by microsud** [comment]
@antagomir I also observed that when others in the lab try the package there is a clash with the diversity function from vegan. Would it be good to rename it maybe calculate_diversity?

**Comment by antagomir** [comment]
In fact I just changed the name to 'global' last week. This better reflects the fact that the function calculates not only diversities but also other global indicators of the overall ecosystem state (dominance, rarity..). I am still thinking if it should be global_indices or for clarity but preferred the shorter 'global' for now. The diversity function is deprecated but still functional.

**Comment by antagomir** [comment]
Ok, there are now distinct functions to calculate various indices for richness, diversities, evenness, dominance, and rarity as described in the package vignette (see [README](https://github.com/microbiome/microbiome) for links)
