### ISSUE TITLE
read_phyloseq

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#37]
Would be good to complement the write_phyloseq function with a read_phyloseq that knows how to read such data back in R. What you think ?

**Comment by microsud** [comment]
@antagomir sounds good. I will give it a try!

**Comment by antagomir** [comment]
Hi, now it turned out we would have one user for this. Possible to create soonish ?

**Comment by microsud** [comment]
Yes! will looking into this ASAP.

**Comment by antagomir** [comment]
I just added an [example on creating a phyloseq object](https://github.com/microbiome/microbiome/blob/devel/vignettes/Data.Rmd) once the CSV data has been read in R. This could help, you just need to add the read.table/read.csv parts etc and wrap these into a function that returns a phyloseq object,

**Comment by microsud** [comment]
@antagomir now I hope the read_phyloseq can be available to early users now :)
