### ISSUE TITLE
plot_taxa_prevalence

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#41]
Format the code so that line widths are <80 characters (Bioc style requirement).

Also do for other functions maintained.

**Comment by antagomir** [comment]
Pls take into account. 

* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * CONSIDER: Shortening lines; 306 lines (2%) are > 80 characters
      long.
    * CONSIDER: Replacing tabs with 4 spaces; 3 lines (0%) contain
      tabs.
    * CONSIDER: Indenting lines with a multiple of 4 spaces; 688 lines
      (6%) are not.

**Comment by microsud** [comment]
@antagomir this has been fixed for some time now. I will close this issue
