### ISSUE TITLE
exclude_samples and exclude_otus

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#42]
would be useful functions sometimes.. to be implemented.

**Comment by microsud** [comment]
@antagomir is it something on the lines of subset_taxa and subset_samples functionality of Phyloseq? They work well in my experience.

**Comment by antagomir** [comment]
Yes, complementary. Conceptually closer to phyloseq::prune_samples and prune_taxa. But instead of selecting a subset ie including specific samples, this could be used to explicitly exclude / throw out some samples.

**Comment by microsud** [comment]
@antagomir okay. This can also be done in phyloseq [https://github.com/joey711/phyloseq/issues/618]

**Comment by antagomir** [comment]
Interesting, thanks! However note that subset_samples and prune_samples are different. Here I was thinking of an opposite for prune_samples, ie samples could be excluded by listing their names. The subset_samples requires that the user checks what metadata field contains the sampleID and this can vary. 

Anyways, I can handle this later. And/or it can be submitted to phyloseq package as a PR as it would fit well there as well. Let's see.
