### ISSUE TITLE
import_biom

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#44]
We should consider rewriting phyloseq::import_biom to circumwent the problems and to remove the dependency. Same applies to many other phyloseq functions that are currently being imported.

**Comment by microsud** [comment]
The alternative is maybe to use '''read_biom''' function from biomformat/biom package for R. Also do you want to replace '''out_table(pseq)'''    and '''taxa_table(pseq)''' '''sample_data(pseq)''' and related functions?

**Comment by antagomir** [comment]
Replacing one dependency with another would not be the solution. So perhaps we just keep it as is for now, unless there is an easy way to reimplement. 

This was a response to the initial feedback from BioC to reduce the number of dependencies. But it is not optimal to reimplement tools that are already available, except when really necessary to circumvent bottlenecks. For basic operations such as otu_table, taxa_table, and sample_data, better stick with the existing ones. We should do this where relatively easy, otherwise just use what there is. Closing this now, perhaps we have to come back to this.

**Comment by microsud** [comment]
Okay. I was thinking the same since biom package is standard for handling
biom files this is needed if we want to ease the use of microbiome package
for seq data. As you said we can address this later if the support for biom
is stopped.
