### ISSUE TITLE
Feature request: pre-processing-quality-control 

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiome#47]
https://academic.oup.com/bioinformatics/article/33/8/1179/2907823/Scater-pre-processing-quality-control 

This article addresses pre-processing-quality-control which is crucial for microbiome data also. Maybe we can try to incorporate this in the next version update?

**Comment by antagomir** [comment]
Good. However as this already is an R package of its own we should not replicate that work in our R package. But we could perhaps augment the tutorial as it is useful to have complete workflow examples from raw data to visualization.

**Comment by microsud** [comment]
Yes agreed! including in tutorial is better also for users to understand the importance of quality control in seq data.

**Comment by microsud** [comment]
We have now included this in the [tutorial](https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/set-up-and-pre-processing.html). Will close this issue for now.
