### ISSUE TITLE
Unable to install microbiome package

### ISSUE THREAD

**Issue by yugi1001** [microbiome/microbiome#49]
Hi,

I used to have an installed version of mcirobiome in RStudio which stopped working. I could never invoke the library or the functions in it. So I removed the folder from the win-library directory. But I am now unable to install it again as I keep getting the below error.

install_github("microbiome/microbiome")
Downloading GitHub repo microbiome/microbiome@master
from URL https://api.github.com/repos/microbiome/microbiome/zipball/master
Installation failed: cannot open file 'C:/Users/yugandhar.reddybs/AppData/Local/Temp/Rtmp2JVzOP/devtools1844756e4631/microbiome-microbiome-a708087/inst/extras/ghpages/inst/extras/microbiome.Rcheck/00_pkg_src/microbiome/vignettes/Betadiversity_files/figure-markdown_strict/heterogeneity-example2bbb-1.png': No such file or directory

my system information is as below:
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

How can I get over this problem?

Thanks in advance,
Yugandhar

**Comment by antagomir** [comment]
Thanks ! This may be due to some features in the devtools package. I tried to fix now. If you can test & report back it would be great.

**Comment by yugi1001** [comment]
Hi Leo,
Many thanks for picking this up quickly. I am having the same problem. And interestignly, downloading a Zip file from github and manually installing it also did not work for me.

> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.3.3 
> install_github("microbiome/microbiome")
Downloading GitHub repo microbiome/microbiome@master
from URL https://api.github.com/repos/microbiome/microbiome/zipball/master
Installation failed: cannot open file 'C:/Users/yugandhar.reddybs/AppData/Local/Temp/Rtmp0Y1GnY/devtools22f4229f25a8/microbiome-microbiome-12a25c3/inst/extras/ghpages/inst/extras/microbiome.Rcheck/00_pkg_src/microbiome/vignettes/Betadiversity_files/figure-markdown_strict/heterogeneity-example2bbb-1.png': No such file or directory


Installing a Zip file using Install Packages in RStudio -
> install.packages("C:/Users/yugandhar.reddybs/Downloads/microbiome-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
> library(microbiome)
Error in library(microbiome) : 
  ‘microbiome’ is not a valid installed package

as the folder in the Win-library is labelled as microbiome-master and I also get a prompt when i type library as microbiome-master, I also tried the below.

> library(`microbiome-master`)
Error in library(`microbiome-master`) : 
  there is no package called ‘microbiome-master’
> library(microbiome-master)
Error in library(microbiome - master) : 'package' must be of length 1

**Comment by antagomir** [comment]
Thanks. I tried to fix again. Can you test and report plz.

**Comment by yugi1001** [comment]
It failed again but at some other step I guess.

> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.3.3 
> install_github("microbiome/microbiome")
Downloading GitHub repo microbiome/microbiome@master
from URL https://api.github.com/repos/microbiome/microbiome/zipball/master
Installing microbiome
Installing 1 package: reshape2
Installing package into ‘C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/reshape2_1.4.2.zip'
Content type 'application/zip' length 609209 bytes (594 KB)
downloaded 594 KB

package ‘reshape2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yugandhar.reddybs\AppData\Local\Temp\Rtmpod4qGO\downloaded_packages
Installing 1 package: vegan
Installing package into ‘C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/vegan_2.4-3.zip'
Content type 'application/zip' length 2922841 bytes (2.8 MB)
downloaded 2.8 MB

package ‘vegan’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\yugandhar.reddybs\AppData\Local\Temp\Rtmpod4qGO\downloaded_packages
"C:/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/yugandhar.reddybs/AppData/Local/Temp/Rtmpod4qGO/devtools13683c325a2c/microbiome-microbiome-1cf6d7d"  \
  --library="C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'microbiome' ...
** R
** data
** inst
** tests
** preparing package for lazy loading
Warning: package 'phyloseq' was built under R version 3.3.2
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'ade4'
Error : package 'phyloseq' could not be loaded
ERROR: lazy loading failed for package 'microbiome'
* removing 'C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3/microbiome'
* restoring previous 'C:/Users/yugandhar.reddybs/Documents/R/win-library/3.3/microbiome'
Installation failed: Command failed (1)
> library(microbiome)
Error in library(microbiome) : 
  ‘microbiome’ is not a valid installed package

**Comment by yugi1001** [comment]
Finally...it worked after installing ade4. Many thanks for taking the trouble.

**Comment by antagomir** [comment]
Perfect. Yes the deps do not install automatically yet. I am submitting the pkg to Bioconductor soonish hopefully, that should considerably smoothen the installation.
