### ISSUE TITLE
read_ function examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiome#50]
For functions read_biom2phyloseq, read_csv2phyloseq, read_mothur2phyloseq etc: add runnable examples to Roxygen by addin small examples files in inst/extdata and using system.file("inst/extdata/..", package = "microbiome") to read with the function.

**Comment by antagomir** [comment]
Thanks a lot for working on this. While working on other issues, the standard checks pointed out that there are lines that exceed >80 chars (bioc request to have less than this). So for read_mothur and read_csv I cut these. I also removed the dontrun in the example header, now these are executable. And modified the function names and paths slightly. Moving from inst/extdata/ to extdata/ is necessary to make the tests pass. It depends on configuration which one is used, not a good feature but we have to live with it. Please look at the changes in read_mothur and read_csv and formulate the remaining ones in a similar way. Remove the dontrun. 

It is a good practice to test that the checks pass. This can be done for instance with inst/extras/build.sh but there are also R tools for making the checks.

**Comment by antagomir** [comment]
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * NOTE: Consider shorter lines; 4 lines (0%) are > 80 characters
      long.
    First 4 lines:
      R/read_biom2phyloseq.R:14 #' otu.table.biom <- system.file('inst/extdat...
      R/read_biom2phyloseq.R:15 #' mapping <- system.file('inst/extdata/qiita...
      man/read_biom2phyloseq.Rd:31 otu.table.biom <- system.file('inst/extdat...
      man/read_biom2phyloseq.Rd:32 mapping <- system.file('inst/extdata/qiita...

**Comment by microsud** [comment]
thanks for the update. I will work on it.

**Comment by microsud** [comment]
This is also fixed by @antagomir
