### ISSUE TITLE
taxa names missing from core microbiome heat map

### ISSUE THREAD

**Issue by rachaelantwis** [microbiome/microbiome#59]
Hi, I'm trying to make a heat map of the core microbiome, using the following code:

library(microbiome)
pseq <- final.4
meta <- meta(pseq)
taxonomy <- tax_table(pseq)
pseq.rel <- microbiome::transform(pseq, "compositional")
colnames(tax_table(pseq.rel)) <- c("Domain","Phylum", "Class", "Order", "Family", "Genus")
colnames(tax_table(pseq.rel))
pseq = merge_phyloseq(pseq, tax_table(final.4))

#Simple anlaysis
core.taxa.standard <- core_members(pseq.rel, detection = 0, prevalence = 50/100)
core.taxa.standard
core.taxa.standard = merge_phyloseq(core.taxa.standard, tax_table(pseq))
core.taxa.standard

#Creates phyloseq object for core microbiome
pseq.core <- core(pseq.rel, detection = 0, prevalence = .5)
pseq.core
pseq.core = merge_phyloseq(pseq.core, tax_table(pseq))
pseq.core

#Use relative abundance
prevalences <- seq(.05, 1, .05)
detections <- 10^seq(log10(1e-3), log10(.2), length = 10)
p <- plot_core(pseq.rel, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
    prevalences = prevalences, detections = detections) +
    xlab("Detection Threshold (Relative Abundance (%))")
print(p) 

However, the resulting figure just gives SV's on the y axis, rather than the actual genus name. Do you know how to coerce the proper taxa information back into this object? Some of the code above might be redundant - it was my attempt to fix this problem!

Many thanks

**Comment by microsud** [comment]
Hi @rachaelantwis
Please check this work around for amplicon data.
http://microbiome.github.io/microbiome/CoremicrobiotaAmplicon.html

Best,
Sudarshan

**Comment by rachaelantwis** [comment]
Thank you. I used the dada2 pipeline, so my data are already in R. Do you have code to attach a phyloseq object please?
Many thanks

**Comment by microsud** [comment]
Hi @rachaelantwis 
Thanks for writing. Do you want to convert your DADA2 file into a phyloseq object? if Yes then the original authors of DADA2 and Phyloseq have this workflow: https://f1000research.com/articles/5-1492/v2

Also I assume that the rownames in your case are RSVs. 
You can try to modify the following command from tutorial to avoid them

```{r}
# Dont use this
# We will merge all the column into one except the Doamin as all is bacteria in this case
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species", "OTU"), sep = "_;", remove = TRUE)

# Instead use this :
# We will merge all the column into one except the Doamin as all is bacteria in this case
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "_;", remove = TRUE)
```

Please let me know how if this is helpful.

cheers,
Sudarshan

**Comment by rachaelantwis** [comment]
Thanks for this - it has replaced the SV’s with the taxonomic information, but it has the full list (from Domain to species!), which makes the table look quite busy. It is possible to label with just the Genus? Also it has rearranged the table so the colors no longer group together (i.e. the core isn’t grouped - it is organized by name rather than abundance). Is it possible to change this back?
Many thanks

**Comment by microsud** [comment]
Hi @rachaelantwis 

The following code...
```{r} 
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "_;", remove = TRUE)
```

... is basically the playing ground for names that you want to include or not. This is not the best way but a dirty one to get it done quickly. You can choose which levels you want by removing it. As with before we removed OTU and kept rest. 

```{r}

# If you want to make the heatmap in a customized order you can try to format it using ggplot2.
# 
library(RColorBrewer)
library(ggplo2)

### from the tutorial
df <- healthycore$data 

# get the list of OTUs
list <- df$Taxa 

# check the OTU ids
# print(list) 

# get the taxonomy data
tax <- tax_table(pseq.2)
tax <- as.data.frame(tax)

# add the OTus to the last column
tax$OTU <- rownames(tax)

# select taxonomy of only 
# those OTUs that are used in the plot
tax2 <- dplyr::filter(tax, rownames(tax) %in% list) 

# head(tax2)

# We will merge all the column into one except the Doamin as all is bacteria in this case
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Genus", "Species", "OTU"), sep = "_;", remove = TRUE)

tax.unit$Taxa_level <- gsub(pattern="[a-z]__",replacement="", tax.unit$Taxa_level)

# add this new information into the plot data df

df$Taxa <- tax.unit$Taxa_level

#####
The data frame df contains the data you want to plot. 
# here reorder is the function of interest.
p <- ggplot(df, aes(x=DetectionThreshold, reorder(Taxa, Prevalence), fill=Prevalence))
    p <- p + geom_tile()
    p <- p + xlab("Detection Threshold")
    p <- p + scale_x_log10() + scale_fill_gradientn(colours = rev(brewer.pal(5, "Spectral")))

```
Let me know if this works for you.

best wishes,
Sudarshan

**Comment by rachaelantwis** [comment]
Perfect! Thank you so much!

**Comment by microsud** [comment]
Good! Thanks for the bringing up this issue :)
