### ISSUE TITLE
bioconda install

### ISSUE THREAD

**Issue by nick-youngblut** [microbiome/microbiome#64]
Feature request: make this package available via [bioconda](https://bioconda.github.io/) as has been done with [phyloseq](https://anaconda.org/bioconda/bioconductor-phyloseq).

Due to recent changes in how `r-base` is compiled for bioconda or conda-forge, R package installations using `install.packages()` and `biocLite()` with R installed via conda will now often fail because R cannot find the correct compilers. This happens because the compilers *must* be in the conda environment, but `install.packages()` and `biocLite()` won't know if they are in the environment or not.

Due to this issue, if R is installed via conda (in order to easily incorporate R + Jupyter), R packages like `microbiome` often cannot be installed, because the package isn't available via `conda` and `biocLite()` will likely fail (unless the proper compilers are installed into the conda environment). Thus, anyone using Jupyter for reproducible bioinformatics is left out if the R package isn't available via conda. Anyone can contribute a package to bioconda, but it's probably best if the package developer is in charge of it.

**Comment by antagomir** [comment]
Thanks for the excellent suggestion. This should be important, we aim to respond to this as soon as the time allows.

**Comment by nick-youngblut** [comment]
FYI: the microbiome R package is now available via [Bioconda](https://bioconda.github.io/recipes/bioconductor-microbiome/README.html) (bioc-3.6)

**Comment by antagomir** [comment]
Excellent, many thanks! I think we can close this issue now.
