### ISSUE TITLE
taxa names

### ISSUE THREAD

**Issue by rachaelantwis** [microbiome/microbiome#65]
Hi, I'm using the following to produce a core heat map:

library(microbiome)
pseq.core <- core(relative.abundance, detection = 0.001, prevalence = 95/100)
pseq.core
tax_table(pseq.core) #to get names for comparison (need to go through individually)
#total core abundance in each sample
core.abundance <- sample_sums(pseq.core)
core.abundance
write.table(as.data.frame(core.abundance), file="core.abundance.txt")

#Set different detection levels and prevalence
prevalences <- seq(.5, 1, .5) #0.5 = 95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) #(1e-3) = 0.001% abundance; change "-3" to -2 to increase to 0.01%
p <- plot_core(pseq.core, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
     min.prevalence = 0.01, prevalences = prevalences, detections = detections) +
    xlab("Detection Threshold (Relative Abundance (%))")
print(p) 

but the graph prints with the SV names (i.e. SV1, SV2, SV3 etc) rather than the taxonomic information (i.e. genus). Is it possible to coerce these names into the figure?
Also, is there a way to agglomerate the data at a higher taxonomic level (e.g. family or order) and then look at the core microbiome of that?  

Many thanks in advance

**Comment by microsud** [comment]
Hi!
A work around for this has been mentioned in issue #59 
If there are doubts, let us know.
Best wishes,
Sudarshan

**Comment by rachaelantwis** [comment]
Thanks for this, the heat map was coming up as incomplete but I think it was removing taxa that appeared as NA when I only used:
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Genus"), sep = "_;", remove = TRUE)
tax.unit$Genus <- gsub(pattern="[a-z]__",replacement="", tax.unit$Taxa_level)
Rather than: 
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Phylum", "Class", "Order", "Family", "OTU"), sep = "_;", remove = TRUE)
tax.unit$Taxa_level <- gsub(pattern="[a-z]__",replacement="", tax.unit$Taxa_level)

Possibly? Anyway, my full code is below in case it’s of use to others:

##Core microbiome
library(microbiome)
pseq.core <- core(relative.abundance, detection = 0.001, prevalence = 95/100)
pseq.core
tax_table(pseq.core) #to get names for comparison (need to go through individually)
#total core abundance in each sample
core.abundance <- sample_sums(pseq.core)
core.abundance
write.table(as.data.frame(core.abundance), file="core.abundance.txt")

# Set different detection levels and prevalence
prevalences <- seq(.5, 1, .5) #0.5 = 95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) #(1e-3) = 0.001% abundance; change "-3" to -2 to increase to 0.01%
p <- plot_core(pseq.core, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
     min.prevalence = 0.01, prevalences = prevalences, detections = detections) +
    xlab("Detection Threshold (Relative Abundance (%))")
print(p) 

library(knitr)

#Sort taxa names
df <- p$data
list <- df$Taxa 

# check the OTU ids
print(list) 

# get the taxonomy data
tax <- tax_table(pseq.core)
tax <- as.data.frame(tax)

# add the OTUs to last column
tax$OTU <- rownames(tax)

# select taxonomy of only 
# those OTUs that are used in the plot
tax2 <- dplyr::filter(tax, rownames(tax) %in% list) 

# head(tax2)

# We will merge all the taxa info in - use a different level to "Family" if required
tax.unit <- tidyr::unite(tax2, Taxa_level,c("Phylum", "Class", "Order", "Family", "OTU"), sep = "_;", remove = TRUE)
tax.unit$Taxa_level <- gsub(pattern="[a-z]__",replacement="", tax.unit$Taxa_level)

# add this new information into the plot data df

df$Taxa <- tax.unit$Taxa_level

# you can see now we have the taxonomic information
knitr::kable(head(df))

# replace the data in the plot object
p$data <- df

plot(p + theme(axis.text.y = element_text(face="italic")))

p <- ggplot(df, aes(x = DetectionThreshold, reorder(Taxa, Prevalence), fill=Prevalence))
    p <- p + geom_tile()
    p <- p + xlab("Relative Abundance (%)")
    p <- p + scale_x_log10() + scale_fill_gradientn(colours = rev(brewer.pal(5, "Spectral")))
    p <- p + ylab("Genus")

plot(p + theme(axis.text.y = element_text(face="italic")))


Many thanks!

**Comment by microsud** [comment]
@rachaelantwis Thanks! if you want to do this analysis at higher taxonomic levels then

```{r}

#your original pseq
# if 
colnames(tax_table(pseq)) 
# last column has SVs/OTU ids then you can skip the following five steps and go to aggregate_taxa step.

taxic <- as.data.frame(ps1@tax_table) 
taxic$OTU <- row.names(taxic)
# convert it into a matrix.
taxmat <- as.matrix(taxic)

# convert into phyloseq compaitble file.
new.tax <- tax_table(taxmat)  

# incroporate into phyloseq Object
tax_table(pseq) <- new.tax

# at family level and all unclassified at family level will be put into to "others" 
pseq.fam <- aggregate_taxa(pseq, "Family")

#Set different detection levels and prevalence
prevalences <- seq(.5, 1, .5) #0.5 = 95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) 
#(1e-3) = 0.001% abundance; change "-3" to -2 to increase to 0.01%

p <- plot_core(pseq.fam, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
min.prevalence = 0.01, prevalences = prevalences, detections = detections) +
xlab("Detection Threshold (Relative Abundance (%))")
print(p)

```
Hope this helps.

Cheers,
Sudarshan

**Comment by rachaelantwis** [comment]
Thanks! What's ps1 in the second command? Should this be pseq?

**Comment by rachaelantwis** [comment]
I'm also getting this error:
> pseq.fam <- aggregate_taxa(relative.abundance, "Family")
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

(my pseq file is called relative.abundance)

**Comment by antagomir** [comment]
@microsud may comment the code above - but I would like to mention that the aggregate_taxa and merge_taxa2 functions are available to merge OTUs to higher taxonomic levels before analysis.

**Comment by microsud** [comment]
@rachaelantwis The error mentioned for aggregate_taxa is usually when the last column names in taxonomy table and rownames do not match. Just to make sure, do they match? also if you could provide a reproducible toy data, then it may help me in better resolving this issue.

**Comment by antagomir** [comment]
These are very good points. We will have to look into these but this may take some time.

**Comment by rachaelantwis** [comment]
Here is a screen grab of what I think you want - the row names and OTUs seem to match?
[Untitled.pdf](https://github.com/microbiome/microbiome/files/1578950/Untitled.pdf)

**Comment by rachaelantwis** [comment]
I'm not quite sure how to provide example data?

**Comment by antagomir** [comment]
Well we could try to use one of our own data sets as an example.

**Comment by rachaelantwis** [comment]
If that's possible that would be great, thank you. Does the taxa table below look correct? (Same is in the PDF attached above).

Taxonomy Table:     [27 taxa by 7 taxonomic ranks]:
      Kingdom    Phylum           Class                          Order                    Family               Genus             OTU    
SV 1  "Bacteria" "PAUC34f"        NA                             NA                       NA                   NA                "SV 1" 
SV 2  "Bacteria" "Chloroflexi"    NA                             NA                       NA                   NA                "SV 2" 
SV 3  "Bacteria" "Proteobacteria" "Gammaproteobacteria"          "E01-9C-26_marine_group" NA                   NA                "SV 3" 
SV 5  "Bacteria" "Chloroflexi"    "Caldilineae"                  "Caldilineales"          "Caldilineaceae"     NA                "SV 5"

**Comment by microsud** [comment]
@rachaelantwis Thanks for bringing this issue up. We can improve the function to deal with NA's in the taxonomy. I tested one of my datasets and for now, the fix is:
Before `aggregate_taxa` function, you can convert NA's into some character for e.g. 
```{r}

# the presence of NA is an issue. 
tax_table(ps1)[is.na(tax_table(ps1)[,"Family"])] <- "f__"

# at family level a
pseq.fam <- aggregate_taxa(ps1, level = "Family")

#Set different detection levels and prevalence
prevalences <- seq(.5, 1, .5) #0.5 = 95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) 
#(1e-3) = 0.001% abundance; change "-3" to -2 to increase to 0.01%

p <- plot_core(pseq.fam.rel, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
               min.prevalence = 0.2, prevalences = prevalences, detections = detections) +
  xlab("Detection Threshold (Relative Abundance (%))")
print(p)

```

Let me know if this works for your data too. 

Cheers,
Sudarshan

**Comment by rachaelantwis** [comment]
Thank you for this. This has coerced all of the taxonomic information for a given OTU with NA for family into "f__" as here:

Taxonomy Table:     [464 taxa by 7 taxonomic ranks]:
       Kingdom    Phylum                Class                           Order                Family                         Genus                         OTU     
SV 1   "f__"      "f__"                 "f__"                           "f__"                "f__"                          "f__"                         "f__"   
SV 2   "f__"      "f__"                 "f__"                           "f__"                "f__"                          "f__"                         "f__"   
SV 3   "f__"      "f__"                 "f__"                           "f__"                "f__"                          "f__"                         "f__"   
SV 4   "Bacteria" "Proteobacteria"      "Gammaproteobacteria"           "Oceanospirillales"  "Oceanospirillaceae"           "Pseudohongiella"             "SV 4"  
SV 5   "Bacteria" "Chloroflexi"         "Caldilineae"                   "Caldilineales"      "Caldilineaceae"               NA                            "SV 5"

**Comment by rachaelantwis** [comment]
Is there a way to make it so only the Family column becomes "f__"
Thanks!

**Comment by microsud** [comment]
@rachaelantwis Yes. My bad. 

```{r}
tax_table(ps2)[,level][is.na(tax_table(ps2)[,level])] <- paste0(tolower(substring(level, 1, 1)), "__")
```

**Comment by rachaelantwis** [comment]
Wonderful! Thank you! Full code as follows for others:

#your original pseq/relative abundance file
#if 
colnames(tax_table(relative.abundance)) 
#last column has SVs/OTU ids then you can skip the following five steps and go to aggregate_taxa step.

taxic <- as.data.frame(relative.abundance@tax_table) 
taxic$OTU <- row.names(taxic)
#convert it into a matrix.
taxmat <- as.matrix(taxic)

#convert into phyloseq compaitble file.
new.tax <- tax_table(taxmat)  

#incroporate into phyloseq Object
tax_table(relative.abundance) <- new.tax

ps1 <- relative.abundance
sample_data(ps1)

#the presence of NA is an issue. 
tax_table(ps1)[,"Family"][is.na(tax_table(ps1)[,"Family"])] <- paste0(tolower(substring("Family", 1, 1)), "__")
tax_table(ps1)[,"Order"][is.na(tax_table(ps1)[,"Order"])] <- paste0(tolower(substring("Order", 1, 1)), "__")
tax_table(ps1)[,"Class"][is.na(tax_table(ps1)[,"Class"])] <- paste0(tolower(substring("Class", 1, 1)), "__")

#at family level
pseq.fam <- aggregate_taxa(ps1, level = "Family")

#at order level
pseq.order <- aggregate_taxa(ps1, level = "Order")

#at class level
pseq.class <- aggregate_taxa(ps1, level = "Class")

#Set different detection levels and prevalence
prevalences <- seq(.5, 1, .5) #0.5 = 95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) 
#(1e-3) = 0.001% abundance; change "-3" to -2 to increase to 0.01%

p <- plot_core(pseq.fam, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
               min.prevalence = 0.2, prevalences = prevalences, detections = detections) +
  xlab("Detection Threshold (Relative Abundance (%))")
print(p)

**Comment by microsud** [comment]
@rachaelantwis Thanks for putting this together!
All the best for your analysis!
Cheers,
Sudarshan

**Comment by rachaelantwis** [comment]
Thanks!
