### ISSUE TITLE
rda analysis

### ISSUE THREAD

**Issue by AndreaQ7** [microbiome/microbiome#66]
Hello everyone, I'm trying to use microbiome tutorial for rda analysis .. the commands should be like : 

> rda.result <- vegan::rda(t(otu) ~ factor(metadata$time),na.action = na.fail, scale = TRUE) 

but if i want to test rda for multiple variables contained within metadata how can I perform this analysis? thanks in advance
An.

**Comment by antagomir** [comment]
Here you are using the rda function from the vegan package. See the man page for this: help(rda)
