### ISSUE TITLE
plot_composition() plots OTU number insead of Species/Genus/family

### ISSUE THREAD

**Issue by wolass** [microbiome/microbiome#7]
Please clarify if this is intentional and propose a possible workaround.

**Comment by antagomir** [comment]
The following example, for instance, indicates the number of reads (or in this particular data, phylogenetic microarray signal) for each phyla. It is also possible to use relative abundances and some other transformations instead via the transform argument. If you prefer other options, could you clarify what these would be ?

library(microbiome)
data("dietswap")
plot_composition(dietswap, taxonomic.level = "Phylum")

**Comment by microsud** [comment]
Check this thread #14 `plot_composition` updated to include taxonomy information instead of OTU number. [https://github.com/microbiome/microbiome/issues/14](url)
