### ISSUE TITLE
Group-wise comparisons of microbiome composition

### ISSUE THREAD

**Issue by Stabilo12** [microbiome/microbiome#70]
I'm wondering how I can transform my phyloseq data in the right format so I can investigate the top factors that separating the groups. 

This doesn't work seem to work: 
pseq.rel <- microbiome::transform(pseq.test, "compositional")
otu <- abundances(pseq.rel)
meta <- meta(pseq.rel) 

My otu data contains many zeros, while the peerj32 data doens't. This might be the problem, why the subscript runs out of bounds?  

coef <- coefficients(permanova)["group1",]
**Error in coefficients(permanova)["group1", ] : subscript out of bounds** 

I'm just started to work with phyloseq data, so sorry if this is a strange question or at the wrong place..

**Comment by microsud** [comment]
Hi @Stabilo12 
peerj32 data is from phylogenetic microarray and not sequencing. If your data is 16S sequencing, you will have many zeroes and it is common. 
Is the `coefficients` working with peerj32 dataset? if yes, maybe you are using the wrong value for "group". This is your main variable from a column in sam_data eg. treatment.

Best wishes,
Sudarshan

**Comment by Stabilo12** [comment]
Hi Sudarshan, 
Yes, the peerj32 dataset is working. Indeed  I used the wrong value for "group", because it is eg. "treatment1", which is the name of a column plus "1".. 
Thanks!

**Comment by microsud** [comment]
Great!
