### ISSUE TITLE
Principal components analysis (PCA)?

### ISSUE THREAD

**Issue by Stabilo12** [microbiome/microbiome#71]
Hi,

Maybe a strange question, but I'm wondering if it is possible to do a principal components analysis (PCA) within the microbiome package? If yes, how?

Thanks!

**Comment by microsud** [comment]
@Stabilo12 Thanks for the question. The package does not include this functionality.  Not sure if you are aware of this [Rpubs veganpca](https://rpubs.com/brouwern/veganpca) if not might be useful.

Cheers,
Sudarshan

**Comment by antagomir** [comment]
We could consider adding fast PCA/PCoA/t-SNE wrappers for phyloseq objects. Or simple tutorial examples at least.

**Comment by antagomir** [comment]
We could consider adding simple wrappers for PCA/PCoA/t-SNE for phyloseq objects for fast plotting and exploration. Or some more tutorial examples. The tutorial already gives some examples: http://microbiome.github.io/microbiome/Ordination.html

**Comment by Stabilo12** [comment]
Thank you very much!
I use the ordination tutorial and adding a PCA in it would be great. 
But I'll try to use the veganpca..

**Comment by antagomir** [comment]
I have now added options for PCA (only with Euclidean distances for now), and t-SNE for phyloseq objects. Examples are provided at the [Landscaping page](http://microbiome.github.io/microbiome/Landscaping.html). All feedback welcome.

**Comment by Stabilo12** [comment]
Great I'll try!
