### ISSUE TITLE
Ordispider or centroids in NMDS plot

### ISSUE THREAD

**Issue by rachaelantwis** [microbiome/microbiome#73]
Hello,
I'm trying to create an NMDS plot that shows the centroid of a group of samples. That is - I have repeat samples from multiple individuals and I want to visualise the central position of the repeats for each individual on the NMDS, with lines going out to the associated samples (much like this: https://stackoverflow.com/questions/47516448/how-to-get-ordispider-like-clusters-in-ggplot-with-nmds). 
I've done a fair bit of googling and playing around but I can't seem to get it to work. The best I can get is polygons, which look a bit of a mess! Please can you help?
Many thanks
Rachael

**Comment by microsud** [comment]
You can try the Rhea scripts for this https://peerj.com/articles/2836/
https://lagkouvardos.github.io/Rhea/

**Comment by rachaelantwis** [comment]
Thanks!

**Comment by antagomir** [comment]
Could be potentially added to our tutorials but perhaps not the top priority 1.
