### ISSUE TITLE
data format for Association heatmaps

### ISSUE THREAD

**Issue by khemlalnirmalkar** [microbiome/microbiome#78]
Hello Everyone,
                        I am newbie to R and bioinformatic analysis. I was trying to make "Association heatmap" but  I got stuck in first step itself. I prepared my microbiota containing file and metadata file with txt and csv extension, but I could not load none of these files to start the analysis. The script which I ran......data("metadata.txt") n it says : data set ‘metadata.txt’ not found

Kindly help me, how to start the analysis and which format of file I should make.

Sincerely,
Khem

**Comment by microsud** [comment]
Hi @khemlalnirmalkar ,
Thanks for the query. You can check this [resource](http://www.r-tutor.com/r-introduction/data-frame/data-import) for more information. I will close this issue for now. If you have any queries, will open again.
All the best,
Sudarshan

**Comment by khemlalnirmalkar** [comment]
Hi Sudarshan,
                     Thanks for your useful link. Now its working well.

I have an query regarding co-occurrence analysis.
I am interested to find an interaction or relation between fungal and
bacterial abundance like attached figure  using two sets of data (otus.biom
from 16S and 18S rRNA) from Qiime 1. Please, can you suggest me which kind
of package or tools should I follow?

Any script or link of tutorial will be helpful... :)
I found an analysis SparCC but could not proper tutorial.



Thanks,
Sincerely,
Khemlal


Thanks,

Sincerely,

Khemlal Nirmalkar

(M.Sc. Microbiology)

Doctorate student

Department of Pharmacology

CINVESTAV-IPN, Zacatenco

México City, México

Email ID: Nirmalkar@cinvestav.mx

khemlalnirmalkar@gmail.com
