### ISSUE TITLE
Error when using Kruskall Wallis test

### ISSUE THREAD

**Issue by cwills31** [microbiome/microbiome#79]
Hi,

I keep getting the following error when trying to perform a Kruskall Wallis test using MicrobiomeSeq (my phyloseq object, which contains taxa abundance and metadata, is called "total" and the metadata category I'm trying to compare is "Population"):

> total.norm <- normalise_data(total, norm.method = "log-relative")
> kw_sig <- kruskal_abundance(total.norm, grouping_column = "Population")
Error in kruskal.test.default(data[, i], g = meta_table$Groups) : 
  'x' and 'g' must have the same length

Does anyone have any idea where I'm going wrong?

Thanks

**Comment by antagomir** [comment]
The correct place to send this issue is the "microbiomeSeq" package github page: https://github.com/umerijaz/microbiomeSeq

We are no in "microbiome" package github page, which is different.

We have some plans to merge these packages but for the time being they are separate.
