### ISSUE TITLE
Microbiome R Tutorial for Whole Metagenome Shotgun Sequencing Data

### ISSUE THREAD

**Issue by Rrob123** [microbiome/microbiome#81]
Hi there, I am working with some whole metagenome shotgun sequencing datasets and I am interested in using the microbiome R package for some analyses however the tutorial appears to be focussed on 16s amplicon datasets. Is the package suitable for shotgun data and if so, are there any tutorials for this?

Many thanks!

**Comment by microsud** [comment]
Hi @Rrob123 
If you have a table with binned genomes (or genes/pathways/etc) and their abundances in each sample (like OTU-table) then you can read it in R using `read_phyloseq` function and keep the `type` option as "simple". Then a phyloseq object will be created which can be used with both phyloseq and microbiome R packages. For more information on this: type ?read_phyloseq in the console.
Hope this helps.

Cheers,
Sudarshan
