### ISSUE TITLE
Error - Community divergence calculations

### ISSUE THREAD

**Issue by lwebercoralgirl** [microbiome/microbiome#84]
Hello,
 
I am trying to compute community divergence amongst my samples and I get the following error:

b.pla <- divergence(subset_samples(pseq.rel, water_type == "CANgulf"))

Error in .C("veg_distance", x = as.double(x), nr = N, nc = ncol(x), d = double(N *  : 
  "veg_distance" not available for .C() for package "vegan"

Any idea what that is about? There was recently an incompatibility between phyloseq and vegan versions and I wonder if this is related to that issue. Thanks for your help!

Here are the package versions that I am using when I get this error
> library("phyloseq"); packageVersion("phyloseq")
[1] ‘1.22.3’
> library("vegan"); packageVersion("vegan")
[1] ‘2.5.2’
> library("microbiome"); packageVersion("microbiome")
[1] ‘1.0.2’

**Comment by cbalsa** [comment]
That solution doesn't work.
I have re-installed with several versions of vegan, and none works

**Comment by antagomir** [comment]
Which version of the microbiome package you are using?

**Comment by GreysonBiegert** [comment]
Hi, I'm having a similar issue when using the alpha() function. These are the versions of the packages I have been using most recently:`
> library("phyloseq"); packageVersion("phyloseq")
[1] ‘1.26.1’
> library("vegan"); packageVersion("vegan")
[1] ‘2.5.6’
> library("microbiome"); packageVersion("microbiome")
[1] ‘1.4.2’`

Should I be using a different version?

**Comment by cbalsa** [comment]
I used the following versions:
1.9.15 microbiome, 
1.22.3 phyloseq ,
2.5.6 vegan.

I used 6 or 7 different versions of the vegan package.  But, the divergence function of the microbiome package did not work.

Should I change the version of microbiobe or phyloseq, or both?

**Comment by antagomir** [comment]
I am not able to replicate this bug. Can you provide a reproducible example and/or provide some test data?

**Comment by cbalsa** [comment]
Please try this example:
https://microbiome.github.io/tutorials/Betadiversity.html

The error message appeared in a job of mine, but also in this code

**Comment by antagomir** [comment]
Thanks. I could not replicate the error. However, the examples were otherwise suboptimal and I have now somewhat revised the divergence function and this tutorial page. If the problem persists, we would still need a reproducible example of the error, together with version numbers of the relevant R packages.
