### ISSUE TITLE
richness function

### ISSUE THREAD

**Issue by hermetia** [microbiome/microbiome#88]
Hi all, I just joined Github a moment ago. I have a question on the richness() function. How does the detection threshold relate to my data? And what detection threshold is best to use (or how to decide which threshold to use)?
In R the following explanation is given: "By default, returns the richness for multiple detection thresholds defined by the data quantiles. If the detection argument is provided, returns richness with that detection threshold."
But somehow my data give identical values of richness for all quantiles. Why does that happen?
Thanks in advance.

**Comment by antagomir** [comment]
Thanks. We have received other similar comments and need to consider a better solution. 

1) The different quantiles can give identical values in particular when the data has many zeroes. Then the different quantiles may yield identical cutoff values.

2) As a default choice, detection = 0 is a good option. It denotes the observed presence / absence of a particular OTU.
