### ISSUE TITLE
Simpson evenness question

### ISSUE THREAD

**Issue by janetw** [microbiome/microbiome#89]
Hello, Thank you for the package. I am trying to use it to calculate Simpson evenness. When I look at the definition of Simpson evenness, I thought it is supposed to be the inverse Simpson value divided by richness (i.e. (1/D)/S, where 1/D is the Inverse Simpson value and S is the richness), correct? But when I do the calculation by hand from the output of the global() on a phyloseq object, that is not the value that I get. Any suggestions on where I might be going wrong would be greatly appreciated. 

Thanks!
Janet
[Example_output.xlsx](https://github.com/microbiome/microbiome/files/2346568/Example_output.xlsx)

**Comment by antagomir** [comment]
Great. Thanks for the report. I fixed something, and I think it works now (see example below). If it does not work, can you kindly provide a reproducible example?

```
library(devtools)
install_github("microbiome/microbiome", ref = "devel")
library(microbiome)
data(dietswap)
g <- global(dietswap)
e <- evenness(dietswap)
plot(e$simpson, g$diversities_inverse_simpson / g$richness_0); abline(0,1)
```

**Comment by janetw** [comment]
Thanks! That corrected the values for the Simpson Evenness, but I am now getting some errors. 
Error in object.size(obj) : could not find function "object.size"

Error in capture.output(base::print(functionCall[[1]])) : 
  could not find function "capture.output"

But it could be that I just don't know how to correctly update that package. I just ran the code similar to what you had above and then re-ran my code.

Thanks,
Janet

**Comment by antagomir** [comment]
Object.Size function is not from our pkg. You can try to restart R

**Comment by janetw** [comment]
Thank you!
