### ISSUE TITLE
the plot_composition() plots OTUs position inconsitently across samples

### ISSUE THREAD

**Issue by wolass** [microbiome/microbiome#9]
In order to easily visually compare samples, I would suggest to plot always the OTUs in the same "level" of a plot. 

The way plot_composition() works right now is to plot the OTUs based on their abundance: the most abundant at the bottom of the bar and the least abundant at the top. 

I think there should be a possibility to override this. So that I always would get OTU nr 1 on the bottom and OTU 100 on top. based on their abundance in the whole database (not just restricted to one sample)

**Comment by wolass** [comment]
even the otu.sort= does not change the order of OTUs in a bar graph

**Comment by antagomir** [comment]
Hmm I have it working with 

library(microbiome)
data("dietswap")
pseq <- subset_samples(dietswap, group == "DI" & nationality == "AFR")

These give the same result:
plot_composition(pseq, taxonomic.level = "Phylum")
plot_composition(pseq, taxonomic.level = "Phylum", otu.sort = "none")

This gives custom ordering
otus <- sample(taxa_names(tax_glom(pseq)))
plot_composition(pseq, taxonomic.level = "Phylum", otu.sort = otus)

If you do not agree, could you provide a reproducible example ?
