### ISSUE TITLE
Error in Cross-correlating data sets

### ISSUE THREAD

**Issue by emankhalaf** [microbiome/microbiome#91]
Hello,
I try to find a correlation between taxa at genus level and different covariates of my dataset, for example genotype. I used this code:

#subset samples
```{r}
bloc = c("GroupB")
# Here's the recommended/intended one line
crop_working_bloc = subset_samples(crop_working, Group %in% bloc)
crop_working_bloc
```

#agglomerate to the genus level
```{r}
cropag = tax_glom(crop_working_bloc, taxrank = "Genus")
```

```{r}
otu = otu_table(cropag)
genotype = meta(cropag)$CropGenotype
```

```{r}
x <- log10(otu)
```

```{r}
y <- as.matrix(genotype)
```

```{r}
correlations <- associate(x, y, method = "spearman", mode = "matrix", p.adj.threshold = 0.05, n.signif = 1)
```

I got this error:
Error in cor.test.default(xi, unlist(y[, j], use.names = FALSE), method = method, : 'x' and 'y' must have the same length

It is unrealistic to get the number of taxa and samples of the same length in a single matrix???

Please help, I need to know how to figure it out
Thanks

**Comment by microsud** [comment]
hi @emankhalaf ,
Thanks for writing to us. Could you please send

```{r}
# what are the values from running these commonds below?
dim(x)  
dim(y)  

only number of samples need to be same.
```

Best wishes,
Sudarshan

**Comment by emankhalaf** [comment]
```{r}
dim(x)
```
[1] 989  41

```{r}
dim(y)
```
[1] 41  1

**Comment by emankhalaf** [comment]
I selected another variable which is sampleID to match exactly the otu table, and I transposed the matrix to match x factor, but still have the same error???

I appreciate your help.
Thanks
Eman

**Comment by microsud** [comment]
Try transposing X by

X <- t(X) 

Then it should match.

**Comment by antagomir** [comment]
Yes. Typically OTU table is taxa x samples and metadata is samples x features. Perhaps we need to clarify examples / documentation. 

Another point: instead of log10(otu) you should probably consider using clr-transformed abundances (see transform function) or DESeq2.

**Comment by emankhalaf** [comment]
Hello, 
I have a new issue using the same code 
Error in cor.test.default(xi, unlist(y[, j], use.names = FALSE), method = method, : 'y' must be a numeric vector

So how can I correlate the otu_table abundances with non-numeric variables?
Any suggestions in microbiome/microbiome

**Comment by emankhalaf** [comment]
By the way, I am using  pearson method for categorical variables

**Comment by antagomir** [comment]
Can you provide a reproducible example with one of our example data sets, or a simple toy data set that can be generated with a few lines of code? This would make debugging easier.

**Comment by emankhalaf** [comment]
I can send it to your e.mail if you don't mind.

I followed your recommendations and got this error

```{r}
otu = otu_table(cropag)
genotype = meta(cropag)$CropGenotype
```


```{r}
otut <- t(otu)
```

```{r}
x <- transform(otut, "clr")
```

```{r}
y <- as.matrix(genotype)
```

```{r}
correlations <- associate(x, y = NULL, method = "pearson", mode = "table", p.adj.threshold = 0.05, cth = NULL, order = FALSE, n.signif = 1, p.adj.method = "fdr", verbose = FALSE, filter.self.correlations = FALSE)
```

```{r}
p <- heat(correlations, "x1", "x2", fill = "Correlation", star = "p.adj", p.adj.threshold = 0.05) 
```

Error in `[<-`(`*tmp*`, as.character(df[i, Xvar]), as.character(df[i,  : 
  subscript out of bounds.

However, I need to correlate taxa with covariates not with itself.

**Comment by emankhalaf** [comment]
I tried 
```{r}
theme_set(theme_bw(20))
df <- correlations
p <- ggplot(df, aes(X1, X2, group=X2)) 
p <- p + geom_tile(aes(fill = Correlation)) 
p <- p + geom_text(aes(fill = df$Correlation, label = round(df$Correlation, 1)), size = 2) 
p <- p + scale_fill_gradientn("Correlation", 
                      breaks = seq(from = -1, to = 1,  by = 0.25), 
                      colours = c("blue", "white", "red"), 
                  limits = c(-1, 1))
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) 
p <- p + xlab("") + ylab("")
print(p)
```
as it is self-correlation, I got nonsense graph (line) 
Also why I still have the same error even when using pearson method (Error in cor.test.default(xi, unlist(y[, j], use.names = FALSE), method = method, : 'y' must be a numeric vector)

**Comment by emankhalaf** [comment]
hello, I am still here

**Comment by antagomir** [comment]
Hi, nice. I am here .. apologies for the delays, perhaps it is good to note that this issue reporting functionality is not an online chat and replies may take some time.

It seems to me that you are using two different versions of the variable names "x1" vs "X1". Which one is correct? Check names(correlations) or colnames(correlations) and use the correct version of the name.

If you have a chance to use a small script generate similar example data in this bug report then that would help to debug? Or you can send a script and small Rdata file by email.

**Comment by emankhalaf** [comment]
Hi,
It is working now using codes in microbiome/microbiome package. I realized that I can not build a correlation between otu counts and a categorical variable. What I am doing is to use Spearman correlation and cross correlating the taxa to itself to find co-occurrence correlation of certain taxa.
The issue now is the heatmap display is using OTUID not the genera names. I applied tax_glom before running the correlation function, but it did not make any difference.
May you please suggest a solution to display the heatmap at genus level.
Thanks
Eman

**Comment by antagomir** [comment]
1) you can just pick the genus-level abundance matrix (oFbtained with tax_glom) using the "abundances" function. And then calculate correlations with that matrix. 

2) there are much better ways to construct microbiome co-occurrence networks. Check for instance SPIEC-EASI. There are many reviews on this topic. For instance by Karoline Faust by also by others.

**Comment by microsud** [comment]
You find information on how to get taxa  names  for amplicom sequencing data here https://goo.gl/CPChhd see section for composition analysis and network inference. Hope this helps.

**Comment by emankhalaf** [comment]
Much thanks.
Eman

**Comment by emankhalaf** [comment]
Actually abundances function is doing the same job as otu_table(object). So, even after agglomeration, the matrix has to be numerical. The problem the codes are not dealing with phyloseq object, everything is done on the otu matrix??? and there is no option in heat function to display genera (it deals with mathematical matrix)??

**Comment by antagomir** [comment]
In fact the heat function operates on a data.frame. This could be expanded to phyloseq objects and matrices but not done currently. It would help to have a look at the manual page example in the heat function, and compare if your input is of the same form.

SPIEC-EASI should work (if there are no association reported then it suggests that there are no associations in fact). But check that the input is in correct form (absolute counts?)

**Comment by antagomir** [comment]
COnclusion: we might like to improve the heat function later.

**Comment by emankhalaf** [comment]
You paid my attention to an important point, I applied SPIEC-EASI on the entire object, but the correlation matrix here came from calculations on the core microbiome at prev.threshold 50%. 

For the taxa names display, I thought about creating a csv file from the correlation table and replace features ID with their taxonomic id at genus level and convert the file in R as a dataframe and run heat. It sounds tedious and prone to mistakes??

**Comment by antagomir** [comment]
Yes
