### ISSUE TITLE
Issues for Correlation analysis between microbiota and metadata by Heatmap

### ISSUE THREAD

**Issue by khemlalnirmalkar** [microbiome/microbiome#93]
Hello Microbiome Group,
                                       I am a bit confused regarding the correlation between microbiota and metadata by Heatmap using Microbiome package. Do I need to normalize or make any changes in my data before starting the analysis?
I tried directly using the relative abundance of bacteria which I got from QIIME 1 (L6.txt; genus level) file and metadata like glucose, triglycerides, cholesterol etc. (I have around 25 type of metadata), but could not find any significant relationship.
I did try with sample files which are available in tutorial, and  I could reproduce the same results but not for my data. I tried to download the sample files from the tutorial but I failed.
Kindly help me, I am totally new to this. If someone can help me to do formatting regarding input files or any modification in the data, I will be grateful.

Thanks in advance
Sincerely,
Khemlal

**Comment by microsud** [comment]
Hi @khemlalnirmalkar 
Every data has it own challenges. You may need to process data separately from what was used for the example dataset in microbiome package. Sparsity is a characteristic feature of microbiome sequencing data. A good read is [here](http://www.nrcresearchpress.com/doi/full/10.1139/cjm-2015-0821?src=recsys&#.W8u3HmgzY2w) 
hope this helps to guide your analysis.

cheers,
Sudarshan
PS: if you don't find correlation, then probably there is none ;)
