### ISSUE TITLE
Error with microbiome::diversities()

### ISSUE THREAD

**Issue by sdhutchins** [microbiome/microbiome#95]
While attempting to generate the different diversity measure, I am getting an error...

Whether I edit the data or not, one of the diversities won't generate and this is the same data file I've been using for months.

## Code

```r
divs <- microbiome::diversities(phyloseq_object, index = "all")
```
## Error
`Error in as.fisher(x) : function accepts only integers (counts)`

**Comment by antagomir** [comment]
Thanks for reporting! Should work now if you update to the latest github devel version. Let us know if problems persist.
