### ISSUE TITLE
Why does this package rely on R 3.5.0?

### ISSUE THREAD

**Issue by grabear** [microbiome/microbiome#99]
What reason does this package rely on the most up to date R?  I know I like to have it installed, but it makes it really impossible to use your package on 3.4.* or even 3.3.*

I tested a build myself to see, and it works with 3.4.4.  https://travis-ci.com/grabear/microbiome/builds/95194868

I'm not sure how to test other versions of R, but it's worth looking into.

**Comment by grabear** [comment]
It also works with R version 3.3.3:
https://travis-ci.com/grabear/microbiome/jobs/166038936

**Comment by antagomir** [comment]
Thanks. This is a fair point. It does not seem to conflict with Bioc guidelines, so this change should be fully ok. I saw a PR that was then closed before merging. Was that intended?

**Comment by grabear** [comment]
No I did not mean to do that, but I'd like to issue another one after some more testing if that's alright?

**Comment by grabear** [comment]
@sdhutchins

**Comment by antagomir** [comment]
Yes, you're welcome.

**Comment by grabear** [comment]
I deleted my old fork, because I pushed to the master.  In my new fork, I've set up 2 separate buffer branches to work on this:
![image](https://user-images.githubusercontent.com/20953530/50245984-a2ef9280-0399-11e9-8c2d-0f87758f2db8.png)

It's a bit much, and it's going to take a while, but I thought "why not?"

I'll use this Issue for updates on the project.

**Comment by antagomir** [comment]
Great 👌

**Comment by grabear** [comment]
https://travis-ci.com/grabear/microbiome/builds/95331829

It seems that it will build for R 3.3.0.  This is the same R version that vegan and phyloseq depend on so that makes sense.  Overall I think this will be super helpful!  I'll make a PR shortly.

**Comment by antagomir** [comment]
Great, many thank! I will merge shortly.
